### ISSUE TITLE
[Suggestion] TXT or JSON banlist.

### ISSUE THREAD

**Issue by Bluscream** [RaidMax/IW4M-Admin#1]
It would be great to have API-like access to banlists. So i would request a TXT banlist like the [echolon one](http://repz.eu/echelon/banlist.php). Maybe also a JSON version for more performance.

**Comment by RaidMax** [comment]
There actually was one, accidentally removed it when I redid the webfront. Will reactivate it in next release.

**Comment by RaidMax** [comment]
Have completed code for this feature again. /pubbans
Will push soon.
