### ISSUE TITLE
exe not found

### ISSUE THREAD

**Issue by ryten** [RaidMax/IW4M-Admin#10]
Hello
I'm sorry for the noobie question
I want to execute IW4M-Admin.exe but I can't find an exe file?
https://s18.postimg.org/ix72g66ex/Untitled.png
And I have tried to rename IW4MAdmin.exe.config to IW4MAdmin.exe and I got this:
https://s18.postimg.org/418j8o2qx/Untitled.png

**Comment by shit-ware** [comment]
https://raidmax.org/IW4MAdmin/

Download from there.

**Comment by ryten** [comment]
I don't know what went wrong? is this works with iw4x?
https://s18.postimg.org/z17ffg461/Untitled.png

**Comment by RaidMax** [comment]
Check the log file. Did you not enter your rcon password set in your IW4x server.cfg?

**Comment by ryten** [comment]
I didn't set rcon passwd, do I have to?

**Comment by shit-ware** [comment]
yes

**Comment by ryten** [comment]
Worked just great, and how to make myself as Owner?

**Comment by shit-ware** [comment]
after the exe is running, go into the game and type !owner in chat

**Comment by ryten** [comment]
I have two problems, Messages keep appearing twice on the screen, and the command !mr usually crashes my game.

**Comment by shit-ware** [comment]
double messages are a known bug. dont know about the other

**Comment by RaidMax** [comment]
@ryten check your sv_maprotation dvar in your configuration file. Crashing consistently on map-rotate is almost always a typo in map name or gametype in your server configuration file.

**Comment by ryten** [comment]
Okay I'll check it.
