### ISSUE TITLE
[Enhancement] Command-Line parameter to skip all command line input

### ISSUE THREAD

**Issue by Jawesome99** [RaidMax/IW4M-Admin#114]
What:
A command line parameter that would automatically answer `Y` to all `Y/N` prompts.

Why:
Sometimes, when restarting IW4M-Admin, not all servers might be reachable, IW4M-Admin will block until the user responds to the `Not all servers could be reached, continue? [Y/N]` prompt.

**Comment by RaidMax** [comment]
This is actually a result of a feature request to include this :)
Issue #58 
Before I look into making the change can you try launching with the command
`echo Y | dotnet Lib/IW4MAdmin.dll` and see if that works as a solution

**Comment by RaidMax** [comment]
I'm closing this as no response and the suggested command should work

**Comment by theunclebobbyb** [comment]
> I'm closing this as no response and the suggested command should work

This does not seem to work when using a docker-compose file. I'll keep trying but it would still be awesome to see a config line to allow this.

**Comment by theunclebobbyb** [comment]
> I'm closing this as no response and the suggested command should work

This does actually work. Sorry for the bump. I had to edit the StartIW4MAdmin.sh file and change "dotnet Lib/IW4MAdmin.dll" to "echo y | dotnet Lib/IW4MAdmin.dll". Thank for you still supporting such a great project!
