### ISSUE TITLE
Can you explain some stuff please ?

### ISSUE THREAD

**Issue by BestNoob** [RaidMax/IW4M-Admin#122]
- can you release a package without .NET requirement, and own MySQL integration ?
- is IW4M-Admin using/creating its own xlrstats database ? Or is it B3 BigBrotherBot compatible + XLRstats ?
- is the Anti-Cheat option now for other projects like cod4x or still only for IW4 ?
- it doesnt accept rcon commands from my client but i am registered as owner ? Saying password is incorrect
- how can i best debug it myself ?
- it seems to be not fully cod4x compatible ?! Just fot the other games ?!

**Comment by RaidMax** [comment]
Please join our discord instead of opening issues: https://discord.gg/ZZFK5p3

________________________________
