### ISSUE TITLE
Requirements needs an update 

### ISSUE THREAD

**Issue by cptmacp** [RaidMax/IW4M-Admin#127]
projects need dot net core SDK as well now

using windows 10 1909  (18363)

I installed dot net core 3.1
but it was throwing errors 

"It was not possible to find any installed .NET Core SDKs windows"

"The framework 'Microsoft.AspNetCore.App', version '3.1.0' was not found."

installing dot net core sdk fixes the issue

**Comment by RaidMax** [comment]
It requires the 3.1 hosting bundle. My discord server lists the pre requisites in the information channel. The readme is a bit out of date since the transition to rolling releases

**Comment by cptmacp** [comment]
i close
