### ISSUE TITLE
The application to execute does not exist

### ISSUE THREAD

**Issue by 16BitShooter** [RaidMax/IW4M-Admin#14]
I went to transfer my servers onto a new machine and when I went to run IW4MAdmin it failed. I had still had the 2.1 prerelease so I figured I should update it and it would be fine. After downloading the newest release I extracted everything from the zip into a folder and did the routine. Then I get this; 
![capture](https://user-images.githubusercontent.com/31642248/40948576-37f5d0aa-6837-11e8-9353-049e94029bbb.PNG)

Normally I would try and troubleshoot on my own before asking, but I'm at a loss when it comes to this error. Anyway you should be able to make something of it. Thanks, see ya soon 👍

**Comment by RaidMax** [comment]
Have you installed .NET Core Runtime 2.0.7 or newer?

**Comment by 16BitShooter** [comment]
yes, I have .NET Core Runtime. I can't seem to find the StartIW4MAdmin.cmd that you mentioned.

**Comment by RaidMax** [comment]
@16BitShooter 
Are you sure you downloaded the correct zip folder for the 2.1 release?

![here](http://screen.keylog.me/FeatureSupport.png)


![](http://screen.keylog.me/PostingsBazaars.png)


https://raidmax.org/IW4MAdmin/Download/IW4MAdmin-2.1-stable.zip

**Comment by 16BitShooter** [comment]
I downloaded the zip from this url: https://github.com/RaidMax/IW4M-Admin
Didn't know that was a thing, give me a sec and I'll try it out.

**Comment by RaidMax** [comment]
@16BitShooter 
Downloading from GitHub just give you the source code :) You would have to compile it yourself, but I provide the binaries on my website. Let me know if any more issues.
