### ISSUE TITLE
Automatic ban function to a player who is reported for 4 consecutive occasions or more

### ISSUE THREAD

**Issue by Chenterito** [RaidMax/IW4M-Admin#144]
A configurable function could be added that when detecting that a player is reported 3 or 4 times in a row, the system automatically expels and banns the player.  it can be configurable the ban either temporary or permanent.

**Comment by RaidMax** [comment]
Implemented in https://github.com/RaidMax/IW4M-Admin/commit/d07e67e2698286cc9d0179e6dbce9e07ec873524
Configuration documentation: https://github.com/RaidMax/IW4M-Admin/wiki/Plugins#action-on-report
