### ISSUE TITLE
add an option to change default prefix from ! to whatever

### ISSUE THREAD

**Issue by swifty-tekno** [RaidMax/IW4M-Admin#149]
or even double prefix that would help me

**Comment by diamante0018** [comment]
I also would like a feature like this. But thinking about the implementation, I think the easiest way is to have the default value set to ! like normal, then if the user wishes to change the prefix maybe add a new line in the JSON config where you can change the prefix from ! to a new character.

**Comment by swifty-tekno** [comment]
would it be possible to use a double prefix like !!

**Comment by RaidMax** [comment]
It will be configurable to change to whatever you want

**Comment by RaidMax** [comment]
implemented in 51202e7  
documentation &mdash; https://github.com/RaidMax/IW4M-Admin/wiki/Configuration#application
