### ISSUE TITLE
[Debian 8] SQLite Error 14: unable to open database file

### ISSUE THREAD

**Issue by arjanvlek** [RaidMax/IW4M-Admin#15]
Every time i start iw4madmin i get the following error:

```
{REDACTED}@{REDACTED}:/home/{REDACTED}/iw4madmin# dotnet IW4MAdmin.dll
=====================================================
 IW4M ADMIN
 by RaidMax
 Version 2.1
=====================================================
Fatal error during initialization
Exception: SQLite Error 14: 'unable to open database file'.
Press any key to exit...
```

I installed .net core runtime as per https://www.microsoft.com/net/download/linux-package-manager/debian8/runtime-current.

That page mentioned version 2.1, which gave the same error. I also tried installing version 2.0.7 with `sudo apt-get install dotnet-hosting-2.0.7 aspnetcore-store-2.0.7` to no avail.

What is going wrong here?

**Comment by RaidMax** [comment]
As mentioned in discord use the MySQL provider until I have time to take a look.

**Comment by RaidMax** [comment]
This issue has been fixed in the latest commit. I will be releasing a pre-release build shortly
