### ISSUE TITLE
permban not working on webfront

### ISSUE THREAD

**Issue by swifty-tekno** [RaidMax/IW4M-Admin#152]
![ban not working](https://user-images.githubusercontent.com/68487146/89224119-d6fbe380-d5cf-11ea-872e-ebfb467d7292.png)

**Comment by swifty-tekno** [comment]
tempban works fine in webfront

**Comment by RaidMax** [comment]
Where are you entering it, through the profile or web console. Also did you setup a custom command prefix ?

**Comment by RaidMax** [comment]
Confirmed this works fine with default command settings. Possible that the command was renamed in your config. If so the webfront is currently setup to use "ban" for permanent ban. I will make a change to use whatever name is specified in the config.

**Comment by ChaseHall** [comment]
Confirmed this is a bug, RaidMax said it should be a quick fix.

**Comment by RaidMax** [comment]
This particular issue occurred before the code that created the issue you experienced was added @ChaseHall 
Either way both should be addressed even though they were separate things.
