### ISSUE TITLE
add option on webfront to ban ip

### ISSUE THREAD

**Issue by swifty-tekno** [RaidMax/IW4M-Admin#153]
to be able to add ip and set reason for adding own blocked ip list  ie known hacker ips andvpn ips not caught by plugin ect

**Comment by RaidMax** [comment]
Bans are already IP based, and if you’re banning off of an IP someone hasn’t connected with, it should be done with a firewall rule.
 
If you’re banning subnets it should also be done with a firewall rule.

Trying to ban vpn IPs is useless as they can change as fast as reconnecting. The only defense is a detection service like I use for the plugin.

Adding this functionality won’t improve the current way IWMAdmin bans, which includes IP address automatically.
