### ISSUE TITLE
warnclear command only goes as low as moderator rank even when set to trusted rank

### ISSUE THREAD

**Issue by swifty-tekno** [RaidMax/IW4M-Admin#154]

**Comment by RaidMax** [comment]
All command are config driven 
https://github.com/RaidMax/IW4M-Admin/blob/b044198c6c350e0c013f9859bacf16328ae8dd09/SharedLibraryCore/Command.cs#L105

Additionally default permission is trusted:
https://github.com/RaidMax/IW4M-Admin/blob/b044198c6c350e0c013f9859bacf16328ae8dd09/SharedLibraryCore/Commands/NativeCommands.cs#L146

I was able to warn clear just fine impersonating a trusted user. Sounds like a config issue on your end.
