### ISSUE TITLE
Stats should log weapons/map usage [Feature Request]

### ISSUE THREAD

**Issue by ChxseH** [RaidMax/IW4M-Admin#155]
Like [XLRStats](https://www.xlrstats.com/) IW4MAdmin should be able to show [most used weapons](https://www.repz.pw/xlrstats/1/weapon_stats)/[maps played](https://www.repz.pw/xlrstats/1/map_stats).

Not sure how easy/hard this would be to be implemented, just would be nice to have.

**Comment by Bluscream** [comment]
Why close?

**Comment by ChxseH** [comment]
Closing as [weapons were added](https://i.imgur.com/fal5GtM.png) and that's mainly what I was after.
Cheers.

**Comment by RaidMax** [comment]
Maps and custom integrations are the next planned part of this. Just wanted to get the weapon stats out the door.
