### ISSUE TITLE
Penalties tab

### ISSUE THREAD

**Issue by fRAIKZz** [RaidMax/IW4M-Admin#158]
Just like Echelon, on each players profile has a 'penalties tab'. This is where all the kicks, bans and notices are stored.

Right now these things are stored in the chatlogs. It would be nice to have a special tab for it.

Another request:
If a player is flagged, add the reason next to it where it says FLAGGED.

**Comment by RaidMax** [comment]
So the goal of the player "log" is to have a chronological order events that occurred in the server. So you can see what led up to a penalty etc..
I'm thinking separating those out would defeat that purpose.
However my thoughts for implementation would be to have a "filter" drop down like the overall penalties page has.
In this case it would be a drop down to select the player meta, (chat, penalties etc).
Would something like that work?

**Comment by fRAIKZz** [comment]
It would work perfectly fine!

**Comment by RaidMax** [comment]
implemented in 6e27dd9
