### ISSUE TITLE
Custom Ban Durations

### ISSUE THREAD

**Issue by florian-ha** [RaidMax/IW4M-Admin#159]
The possibility to select custom Ban Durations in the IW4MAdmin panel would be nice to have.

Also, if possible, it would be nice to select the rules as a fixed reason in the panel.

Another idea i had was to give the opportunity to have out of the ordinary Anticheat Metrics colored (for example orange for noticeable high metrics, red for too high). So it's much easier to quickly analyze metrics.

The last idea would be to add the messages which get written by admins via the panel to the chatlogs of players, so you can see the whole conversation a player had with an admin which wasn't ingame.

**Comment by RaidMax** [comment]
Added rules shortcut : https://github.com/RaidMax/IW4M-Admin/wiki/Commands#rules-shortcut
It's not 100% what was requested but it's the current path I want to take.
Anticheat metrics feature cannot be implemented at this time due to how it's calculated.
