### ISSUE TITLE
Ban loop

### ISSUE THREAD

**Issue by Bluscream** [RaidMax/IW4M-Admin#16]
TargetTypeOffenseOriginTime/LeftLoganKickPreviously banned for Previously banned for Previously banned for Previously banned for No recoilIW4MAdmin1 minute(s) ago

This is the latest kick on your website as of now. Pretty sure it shall not be that way, otherwise the msg might get too big too kick

**Comment by RaidMax** [comment]
It has to do with linked accounts, and a bunch of paki's using the same IP addresses. It's an edge case that in an ideal environment wouldn't happened, but thanks to shared IPs and shared GUIDS (ugg) it gets messy. It's probably something I need to make a specific check to see.

**Comment by RaidMax** [comment]
Fixed in commit:
https://github.com/RaidMax/IW4M-Admin/commit/df273118957d5e351480fcd72a07beed2c021a18
