### ISSUE TITLE
Feature request

### ISSUE THREAD

**Issue by swifty-tekno** [RaidMax/IW4M-Admin#160]
add option on webfront player profile for owner to set admins password
some of my admin having trouble setting passes them selves so it would be easier for me to set it for them and msg it to them

another request 
add an option to allow certain players to use vpn on server
ive seen a few times there are false positives saying someone is using vpn when they are not
or would be even nicer for vpn whitelist to either allow all vpn usage 
or only connecting on a certain ip thats flagged as vpn
then i could allow someones ip but still restrict other vpn usage

**Comment by RaidMax** [comment]
Both of these features already exist:

**`runas` command**
https://github.com/RaidMax/IW4M-Admin/issues/126
usage: !runas @123 setpassword newpassword

**VPN Exceptions**
https://github.com/RaidMax/IW4M-Admin/wiki/Plugins#vpn-detection-script-plugin
example ` vpnExceptionIds: [123, 456]`
Bypasses check for entered client ids
