### ISSUE TITLE
Feature Request: Do not display chat history from private servers

### ISSUE THREAD

**Issue by codpcleague** [RaidMax/IW4M-Admin#162]
**Feature Request:** Do not display chat history publicly on the webfront from private servers, which can be distinguished by servers that have a password. 
**Justification:** Privacy and permissions for elevated users who are on private servers because of various reasons such as: VIP only, test servers, etc.
**Priority:** Very low

**Comment by RaidMax** [comment]
WIP update 
![image](https://user-images.githubusercontent.com/6732771/90698418-3865b880-e246-11ea-9c8a-d85433330f65.png)

**Comment by RaidMax** [comment]
implemented in 2e0b1b3

**Comment by Bluscream** [comment]
Why show the messages at all? Just void them or make them admin only, the asterixes are just teasing
