### ISSUE TITLE
Feature request to allow for hosting iw4x folder inside wwwroot for iw4x fast download

### ISSUE THREAD

**Issue by MrHtgreen** [RaidMax/IW4M-Admin#165]
Hello, had an idea which is to add support for the hosting of a users iw4x folder inside the wwwroot folder to allow support for iw4x fast download. Thank you for considering this as it would be very useful.

**Comment by Jawesome99** [comment]
Not really related to IW4mAdmin at all. Create a symlink in the wwwroot folder that points at your iw4x folder, limit access to only the mods and usermaps folders using something like a .htaccess file

**Comment by RaidMax** [comment]
Closing this for now as I'm not planning on implementing at this time.
