### ISSUE TITLE
Adding More Support For T7 (Feature & Enhancements Request)

### ISSUE THREAD

**Issue by LeonLionHeart** [RaidMax/IW4M-Admin#167]
It would be neat to implement the full compatibility of the T7 parser even with the current limitations. 

I'd like to see logging redefined and sorted in a way that works best with the T7 dedicated server.
I was able to pull XUID off a log, however, I was unsuccessful at separating the logs from one server to another. 
Thanks.

**Comment by ChaseHall** [comment]
Some discoveries we made which might be disappointing:

* Chat messages aren't logged at all in the "pre-game" lobby.
* Chat messages don't contain player's XUID. `[chat][Chase] Hello` (at least in the `console_mp.log`)
* However, `status` does get written in the same file, so maybe that helps?

* The log file that actually shows GUID's doesn't get continuously written to, no matter the dvar setting. (in the `gameserver.log`), upon map changing it *does* update however.


```
# console_mp.log

[chat][Chase] chat in game
[chat][Chase] chat in game 2
[chat][Chase] manually running status:
---------- Live ----------
ffotd version 2
playlist 1 version 325120000
protocol 100 version 18532
Local IP: 51.81.75.112:15001
Public IP: 51.81.75.112:15001
Mod Loaded: 771672355/mp_bootsonground
---------- Steam ----------
Server Browser: true
Map: mp_nuketown_x
Gametype: tdm
---------- Lobby Info ----------
We are hosting a lobby with 1 members:
     0: Chase 
---------- Server ----------
map: mp_nuketown_x
num score ping xuid               name             address                  qport  
--- ----- ---- ------------------ ---------------- ------------------------ ------ 
  0     0   69  76561198044408282 Chase            xxx.xxx.xx.xxx:27017(0)   30033
## CHANGING MAP HERE
==== ShutdownGame (1) ====
```

```
# gameserver.log
# Changing map causes gameserver.log to be written to, containing what appears to be some form of identifier of the player.


  0:00 ------------------------------------------------------------
  0:00 InitGame: map mp_nuketown_x; gametype tdm;
  0:19 chat;0;76561198044408282;0;Chase;chat in game
  0:30 chat;0;76561198044408282;0;Chase;chat in game 2
  0:54 chat;0;76561198044408282;0;Chase;manually running status:
  1:13 ShutdownGame
  1:13 ------------------------------------------------------------
```

**Comment by RaidMax** [comment]
Yep unfortunately the partial support of T7 is due to a limitation of the game engine, not IW4MAdmin. IW4MAdmin is able to track player connects/disconnects, but the chat and events are not logged synchronously no matter the settings that're applied. Seems like someone with enough knowledge would need to modify the binary to support synchronous logging and custom log file name support.

**Comment by mikzyy** [comment]
how were you able to pull XUID from log? which log file was it?

**Comment by ChaseHall** [comment]
In that 2nd chunk of code, the gameserver.log, somewhere in /identities/dedicatedpc (not at PC right now) and it updates every map rotate, so in no way is it ideal.

**Comment by RaidMax** [comment]
Closing this for now unless there's a modification with the client that allows synchronous logging
