### ISSUE TITLE
LiveRadar does not show bots

### ISSUE THREAD

**Issue by ineedbots** [RaidMax/IW4M-Admin#168]
It appears that the GUID parser fails to parse the bot's GUID.

```log
[09.18.2020 18:32:09.750] - Warning: Could not parse live radar output: System.Collections.ListDictionaryInternal
[09.18.2020 18:32:09.751] - Debug: Exception[0] Name: System.FormatException
Exception[0] Message: Could not parse client GUID - bot49
Exception[0] Call Stack:    at SharedLibraryCore.Utilities.ConvertGuidToLong(String str, NumberStyles numberStyle, Nullable`1 fallback)
   at LiveRadar.RadarEvent.Parse(String input)
   at LiveRadar.Plugin.OnEventAsync(GameEvent E, Server S)
Exception[0] Source: SharedLibraryCore

[09.18.2020 18:32:09.751] - Debug: Exception[0] Name: System.FormatException
Exception[0] Message: Could not parse client GUID - bot48
Exception[0] Call Stack:    at SharedLibraryCore.Utilities.ConvertGuidToLong(String str, NumberStyles numberStyle, Nullable`1 fallback)
   at LiveRadar.RadarEvent.Parse(String input)
   at LiveRadar.Plugin.OnEventAsync(GameEvent E, Server S)
Exception[0] Source: SharedLibraryCore
```
![image](https://user-images.githubusercontent.com/751729/93656272-53168300-f9e6-11ea-8d59-37d4aedaa711.png)
![image](https://user-images.githubusercontent.com/751729/93656278-5873cd80-f9e6-11ea-9f0b-54a249b402cc.png)

**Comment by RaidMax** [comment]
Do you have IgnoreBots set to false?

**Comment by ineedbots** [comment]
It is set to false

**Comment by RaidMax** [comment]
Are you using the IW4x parser?

**Comment by ineedbots** [comment]
Yes

**Comment by RaidMax** [comment]
Ok I will look into this. Bots worked in the past as that’s how I did a lot of my testing.

**Comment by ineedbots** [comment]
I got it to work, but one caveat is that the bot's name must be the same as their guid.

![image](https://user-images.githubusercontent.com/751729/93680286-ef826900-fa6a-11ea-803a-fffe760f55df.png)
![image](https://user-images.githubusercontent.com/751729/93680511-01fca280-fa6b-11ea-8894-15214c926330.png)

Custom bot names will break the LiveRadar.

**Comment by RaidMax** [comment]
Yep the issue occurs because I changed the way guids are parsed. It used to be that the GenerateGuidFromString handled bot guids, but I moved that out as it's not really the best way to do things. I'll be pushing a fix for this shortly

**Comment by RaidMax** [comment]
Ended up taking a little more time than expected, due to external factors. Update is complete and I will be pushing out an update soon. 
![image](https://user-images.githubusercontent.com/6732771/93817607-d1f60080-fc1e-11ea-9215-93ad0d06ad78.png)

**Comment by RaidMax** [comment]
addressed in 
514af74
