### ISSUE TITLE
[Feature Request] Add a PM system only for admins

### ISSUE THREAD

**Issue by diamante0018** [RaidMax/IW4M-Admin#170]
A PM system that can only be used and seen by privileged clients (trusted and up). 
Something that works like this: "!pma check that player he might be cheating"
Only the admins that are online should see that mesagge. It could be displayed like this: [Owner] Name -> check that player he might be cheating.
And if there are no admins online except you notify the sender, like "There are no other online admins" or something similar.
Other ideas for the name of the command: !adminchat, !ac
Thanks

**Comment by ChaseHall** [comment]
This feature is kind of useless since most clients don't hide commands at all, but still might be useful for the clients that *do* hide messages, I suppose.

**Comment by diamante0018** [comment]
Correct, I can only confirm T5 Tekno hides messages that start with !. Although I'm sure In every client it is possible to develop a script that hides all messages that start with !. So it's not completely useless

**Comment by ChaseHall** [comment]
I don't think you understand what multiple people have told you, without editing the **engine** itself you cannot hide command chat messages. It's highly unlikely IW4x/Pluto will implement this feature.

**Comment by Bluscream** [comment]
Shouldnt you be able to hook the chat message func and return null if msg.startsWith("!")

**Comment by diamante0018** [comment]
Oh, I see chaasehall. I understand it's just that I didn't choose the best words. When I said 'script' I am not referring to IW4M. I am referring to an in-game script that tweaks the game engine.

**Comment by RaidMax** [comment]
implemented in
