### ISSUE TITLE
(Feature Request) more information on ban messages

### ISSUE THREAD

**Issue by swifty-tekno** [RaidMax/IW4M-Admin#171]
rough example
you have been banned - by swifty - reason test - date 26/09/20 - time 07:28 - unban appeal at (serverwebsite)

previously banned - by swifty - reason test - date 26/09/20 - time 07:28 - unban appeal at (serverwebsite)

or if not date and time add what admin banned to message

**Comment by RaidMax** [comment]
There's a pretty short character limit for most games unfortunately

**Comment by RaidMax** [comment]
@swifty-tekno after looking into this more it looks like certain games will be able to handle additional information.

![image](https://user-images.githubusercontent.com/6732771/94582399-cf5c6200-0241-11eb-803a-8f07e30c7aa5.png)

For Tekno, can you provide me with the max number of lines and the max number of `W` characters that can be displayed.
For example in the picture above, we can display 5 lines, with a max character width of 30.

Example to test the max characters:  `clientkick 0 "0123456789abcdefghijklmnopqrstuvwxyz012345 WWWWWWWWWWWWWWWWWWWWWWWWWWWWWW 0123456789abcdefghijklmnopqrstuvwxyz012345 WWWWWWWWWWWWWWWWWWWWWWWWWWWWWW 0123456789abcdefghijklmnopqrstuvwxyz012345"`

**Comment by diamante0018** [comment]
I wouldn't want this much information, I think keeping the kick message as brief as possible is better than adding more information

**Comment by RaidMax** [comment]
It’s not going to be this much info, it’s just going to be formatted better and more consistent

**Comment by swifty-tekno** [comment]
> @swifty-tekno after looking into this more it looks like certain games will be able to handle additional information.
> 
> ![image](https://user-images.githubusercontent.com/6732771/94582399-cf5c6200-0241-11eb-803a-8f07e30c7aa5.png)
> 
> For Tekno, can you provide me with the max number of lines and the max number of `W` characters that can be displayed.
> For example in the picture above, we can display 5 lines, with a max character width of 30.
> 
> Example to test the max characters: `clientkick 0 "0123456789abcdefghijklmnopqrstuvwxyz012345 WWWWWWWWWWWWWWWWWWWWWWWWWWWWWW 0123456789abcdefghijklmnopqrstuvwxyz012345 WWWWWWWWWWWWWWWWWWWWWWWWWWWWWW 0123456789abcdefghijklmnopqrstuvwxyz012345"`

its the same for tekno

**Comment by swifty-tekno** [comment]
![banned](https://user-images.githubusercontent.com/68487146/94630322-54389180-02bd-11eb-9ee3-fae24ac483c2.PNG)

**Comment by RaidMax** [comment]
Closing this as I have created what I feel is a more consistent message
Kick:
```
You have been kicked
Reason - reason here
```
TempBan
```
You have been temporarily banned
Reason - reason here
Time Remaining - 1 hour
```
Ban
```
You have been permanently banned
Reason - reason here
Visit example.com to appeal
```
Note a new configuration option was added: `ContactUri`
You can provide your discord/website/email whatever and that gets plugged into the appeal message.

**Comment by RaidMax** [comment]
One more thing, if text ends up overflowing other games (only tested IW4x), we can tweak the `NoticeMaxCharactersPerLine` per parser to get it to fit properly

**Comment by swifty-tekno** [comment]
> Closing this as I have created what I feel is a more consistent message
> Kick:
> ```
> You have been kicked
> Reason - reason here
> ```
> TempBan
> ```
> You have been temporarily banned
> Reason - reason here
> Time Remaining - 1 hour
> ```
> Ban
> ```
> You have been permanently banned
> Reason - reason here
> Visit example.com to appeal
> ```
> Note a new configuration option was added: `ContactUri`
> You can provide your discord/website/email whatever and that gets plugged into the appeal message.

So I don't need to manually add my discord to localisation

**Comment by RaidMax** [comment]
Correct, just set the ContactUri in your IW4MADMINSettings
