### ISSUE TITLE
Hostname changes every time a server reconnects

### ISSUE THREAD

**Issue by JustMiguelBTW** [RaidMax/IW4M-Admin#176]
Hello,

I have an issue where whenever one of my servers disconnects then reconnects to IW4M it cannot display its name properly. It always changes the name to BlackOpsPublic. Is there a way to fix this issue so I do not have to restart IW4M every time one of my servers disconnects from it?

I have attached a before and after of what happens when one of my servers disconnects then reconnects.

Before I disconnect:
![Screenshot 2020-11-15 143034](https://user-images.githubusercontent.com/65464672/99196006-231dfe80-274f-11eb-8734-22d53872805f.png)

After the server disconnects and reconnects:
![image](https://user-images.githubusercontent.com/65464672/99196034-5791ba80-274f-11eb-9572-5a51940ad6a4.png)

The hostname for the server does not change when looking for it on the Plutonium T6 Server List.

To add some more context, I also updated to your latest version (2020.11.15.1 Prerelease), and the previous updates have not had this issue.

**Comment by RaidMax** [comment]
This “issue” is not really related to IW4MAdmin. It was introduced in the new version of Pluto T6. Traditionally the server name is first read through the value of the sv_hostname dvar. Additionally every time the map changes/loads the server name is printed to the log.
 IW4MAdmin uses both of these methods to determine the name of your server. 
With the new version of Pluto the server name is no longer tied to the sv_hostname dvar.
Instead it is tied to your server key. I do not have the authorization to determine what the name of your server is based on your server key.
The result of this disconnect is the server name printed in the log does not reflect the server name tied your server key, so IW4MAdmin is fed in “bad” data. 
At its root it’s an issue with the Pluto client.

As far as solutions, you should be able to manually set the sv_hostname dvar to match the server key hostname in your server config(s). Secondly there’s an OverrideHostname or CustomHostname property in the IW4MADMINSettings.json that you can set your server name manually.

Let me know if any questions.

**Comment by JustMiguelBTW** [comment]
Thank you!
