### ISSUE TITLE
T4 Parser issues

### ISSUE THREAD

**Issue by ineedbots** [RaidMax/IW4M-Admin#178]
Seems like T4 doesn't work well with IW4M Admin, it seems that people connect multiple times into a match, kicking/banning doesn't kick the target, etc.

**Comment by RaidMax** [comment]
Steam or retail?

**Comment by ineedbots** [comment]
Retail in my case

**Comment by RaidMax** [comment]
> Retail in my case

Using CoD parser for both event and rcon parser?

**Comment by ineedbots** [comment]
Yep

**Comment by RaidMax** [comment]
Will look into it tonight. Might be some small tweaks needed to the status regex.

**Comment by RaidMax** [comment]
Addressed in 5a81d5b.
Tested against steam, which should be the same as retail I think?
Needed to parse the guid as decimal. Also was a small issue with the game time not being able to be parsed as an integer as it's expressed different in the T4 log file.

Parser version to use: `Call of Duty Multiplayer COD_WaW MP build 1.7.1263 CL(350073) JADAMS2 Thu Oct 29 15:43:55 2009 win-x86`

Let me know if any issues. If not I will close this tomorrow.

**Comment by ineedbots** [comment]
It seems to work now!

Just the bots are being ignored when ignorebots are false, but thats fine,

**Comment by RaidMax** [comment]
@ineedbots 
What's the bot GUID showing in status.
On my end it was a hard coded GUID that I added to the bot guid check. 
Was able to track bots fine on my end

**Comment by ineedbots** [comment]
1277538174, it might be different every map rotation, i'll look at the addtestclient func to see what it is doing

**Comment by RaidMax** [comment]
Well that's annoying it was `1075569476` when I was testing.

**Comment by ineedbots** [comment]
It does a hash function on the installed cdkey to generate a bot's guid

**Comment by RaidMax** [comment]
> It does a hash function on the installed cdkey to generate a bot's guid

Amazing... I think I'll need to update the parsing to either see if the bot IP is all 0's or it's not parsed as a valid IP + their ping is 999.

**Comment by ineedbots** [comment]
Seeing that it's specific to the server's cdkey, and is the same every time for that server, couldn't you just add a configuration entry: T4BotGuid

It would require a server owner to input the bot's guid into the configuration, but it'll just be once
