### ISSUE TITLE
[Feature request] Iw4madmin VU

### ISSUE THREAD

**Issue by fRAIKZz** [RaidMax/IW4M-Admin#179]
Would love to see the iw4madmin ported over to VU as well.

If you are a cross community, everything in one tool would be great instead of running different tools in multiple games. Adding iw4madmin eliminates the issue of having multiple tools and multiple databases that makes everything slow.

Would love to see this implemented!

**Comment by Bluscream** [comment]
what's VU?

**Comment by fRAIKZz** [comment]
The new battlefield 3 client. Venice Unleashed created by NoFaTe and his team. [www.veniceunleashed.com](url)
