### ISSUE TITLE
[Feature request] Rules when banning in webpanel

### ISSUE THREAD

**Issue by fRAIKZz** [RaidMax/IW4M-Admin#180]
Since you can add a custom ban reason in the web panel page. Is there a possibility to add rules that have been set in the config displayed as a ruleset for the reason? I have been artistic in paint to show the idea.

![iw4madmin rules](https://user-images.githubusercontent.com/68132791/103141918-0c7aa800-46fc-11eb-8840-6a6a404b5389.png)

**Comment by RaidMax** [comment]
Does something like https://github.com/RaidMax/IW4M-Admin/wiki/Commands#rules-shortcut
work as a compromise?

**Comment by RaidMax** [comment]
Implemented in 95643f6
Also adds configurable ban durations and shortcut for penalty reasons.
Example `!kick @2 ci` -> Player kicked for Connection Interrupted. Reconnect

Config documentation: https://github.com/RaidMax/IW4M-Admin/wiki/Configuration#application
