### ISSUE TITLE
Add toggle option to hide admins in web panel

### ISSUE THREAD

**Issue by sepehr-gh** [RaidMax/IW4M-Admin#185]
Since my own code from [this pull request](https://github.com/RaidMax/IW4M-Admin/pull/182) is not useful to implement a feature that lets owner of server decide if they want to let players see admins in panel, I am creating this issue (feature suggestion) instead. My reasons and idea is written in the pull request.

**Comment by RaidMax** [comment]
Implemented in f984d50
