### ISSUE TITLE
"PrivilegedUserPrivacy" issue

### ISSUE THREAD

**Issue by sepehr-gh** [RaidMax/IW4M-Admin#188]
Hey there. We have discovered that by setting `EnablePrivilegedUserPrivacy` to `true`, privileged users and messages are hidden.

The "Admins" section from top navbar is also gone, but the issue is if you have the link to that section it will still work without logging in:
https://repz.pw/Client/PrivilegedAsync

**Comment by RaidMax** [comment]
Addressed with 
a4bdbca
