### ISSUE TITLE
[Feature Request] SourceMod Port/Intergration

### ISSUE THREAD

**Issue by MrAmos123** [RaidMax/IW4M-Admin#189]
The title really, but I'd like to be able to use IW4MAdmin as the admin tool for Counter-Strike: Global Offensive as opposed to the fragmented admin tools that are available on SourceMod into one nice collective tool that is IW4MAdmin.

**Comment by RaidMax** [comment]
Added with 7e01dc3fc2068dd04e86cb55dd2d49a86f9fcc4f
