### ISSUE TITLE
It was not possible to find any compatible framework version

### ISSUE THREAD

**Issue by MrAmos123** [RaidMax/IW4M-Admin#19]
C:\_Servers\IW4MAdmin>dotnet IW4MAdmin.dll
It was not possible to find any compatible framework version
The specified framework 'Microsoft.NETCore.App', version '2.1.0' was not found.
  - Check application dependencies and target a framework version installed at:
      \
  - Alternatively, install the framework version '2.1.0'.

***

I installed first, 2.0.7 same error, then I installed 2.0.9. There isn't a 2.1.0 RunTime available for download.

Here are the installed versions of what I installed on .NET RunTime: 
https://i.imgur.com/nm28lL0.png

***

EDIT: Resolved via using Stable Build instead of development builds. My fault.

**Comment by MrAmos123** [comment]
Resolved

**Comment by RaidMax** [comment]
If you want to use the pre release build, the runtime is available at 

https://www.microsoft.com/net/download/thank-you/dotnet-runtime-2.1.2-windows-hosting-bundle-installer
