### ISSUE TITLE
Advanced stats do not record the favorite weapon in iw5

### ISSUE THREAD

**Issue by Chenterito** [RaidMax/IW4M-Admin#194]
What the title says, in iw5 it does not register the favorite weapon, I checked in several statistics of some players and it only shows "iw5" in the field of favorite weapon in all reviewed.
Example:
[1](https://gyazo.com/9293ad43c71bde3b6be2e50b652c36ad)
[2](https://gyazo.com/326053ec5114ef6d7df2dcce2b049c5c)
[3](https://gyazo.com/e1179fee36221f4fe234edc37c96937b)

**Comment by RaidMax** [comment]
Can you verify that your StatsPluginSettings contains the iw5 weapon parse entry https://github.com/RaidMax/IW4M-Admin/blob/cf6d71a8e52d47ab65d210521b16cf8c3452d647/Plugins/Stats/Config/StatsConfiguration.cs#L35

**Comment by Chenterito** [comment]
As I do it, what I have in the Plugins folder are .dll files
[View Folder](https://gyazo.com/ee152db7efe2cf297cc9540317bf5217)

**Comment by RaidMax** [comment]
What does your `StatsPluginSettings.json` file look like in `Configuration` folder

**Comment by Chenterito** [comment]
`{
  "EnableAntiCheat": null,
  "KillstreakMessages": [
    {
      "Count": -1,
      "Message": "Try not to kill yourself anymore"
    },
    {
      "Count": 5,
      "Message": "Great job! You're on a ^55 killstreak!"
    },
    {
      "Count": 10,
      "Message": "Amazing! ^510 kills ^7without dying!"
    },
    {
      "Count": 15,
      "Message": "Amazing! ^515 kills ^7without dying!"
    },
    {
      "Count": 20,
      "Message": "Amazing! ^520 kills ^7without dying!"
    },
    {
      "Count": 25,
      "Message": "You better call in that nuke, ^525 killstreak^7!"
    }
  ],
  "DeathstreakMessages": [
    {
      "Count": 5,
      "Message": "Pick it up soldier, you've died ^55 times ^7in a row..."
    },
    {
      "Count": 10,
      "Message": "Seriously? ^510 deaths ^7without getting a kill?"
    }
  ],
  "TopPlayersMinPlayTime": 10800,
  "StoreClientKills": false,
  "MostKillsMaxInactivityDays": 30,
  "MostKillsClientLimit": 5,
  "EnableAdvancedMetrics": true,
  "WeaponNameParserConfigurations": [
    {
      "Game": "IW3",
      "Delimiters": [
        "_"
      ],
      "WeaponSuffix": "mp",
      "WeaponPrefix": null
    },
    {
      "Game": "IW4",
      "Delimiters": [
        "_"
      ],
      "WeaponSuffix": "mp",
      "WeaponPrefix": null
    },
    {
      "Game": "IW5",
      "Delimiters": [
        "_"
      ],
      "WeaponSuffix": "mp",
      "WeaponPrefix": "iw5"
    },
    {
      "Game": "T6",
      "Delimiters": [
        "_",
        "+"
      ],
      "WeaponSuffix": "mp",
      "WeaponPrefix": null
    }
  ],
  "ServerDetectionTypes": null,
  "AnticheatConfiguration": {
    "Enable": false,
    "ServerDetectionTypes": {},
    "IgnoredClientIds": [],
    "IgnoredDetectionSpecification": {
      "IW4": {
        "Chest": [
          "m21.+"
        ],
        "Recoil": [
          "ranger.*_mp",
          "model1887.*_mp",
          ".+shotgun.*_mp"
        ],
        "Button": [
          ".*akimbo.*"
        ]
      }
    }
  }
}`

**Comment by RaidMax** [comment]
I was able to determine the issue: https://github.com/RaidMax/IW4M-Admin/blob/cf6d71a8e52d47ab65d210521b16cf8c3452d647/Plugins/Stats/Client/WeaponNameParser.cs#L53

I will make the change tomorrow, thanks for the report.

**Comment by RaidMax** [comment]
Should be addressed with fd6ab7f
