### ISSUE TITLE
You have a cheater problem, lets work together 

### ISSUE THREAD

**Issue by BestNoob** [RaidMax/IW4M-Admin#197]
You guys from cod4x seems not to be interested into perfect servers or cheat protection but it is really important .... i checked it, you have a huge amount of cheaters ......

Check the posts i have made https://cod4x.me/index.php?/profile/8815-bestnoob/

**So i ask you again do you want to work together with me ?**
for cod4x this means:

- creating a online database for cheater detection (sourcebans)
- and / or working together with PBBans
- porting and integrating this anti cheat to cod2, cod5, BFBC2, BF2 and other games
- creating a parser for PBGUID / EAGUIDE / STEAMID for a unified ban system
- reducing PunkBuster to MD5 and system process checks to make it more compatible

My Server project is to huge for just one person
https://discord.gg/A7vtjmw

I have a dream: I want to establish a new quality for server hosting and for this classic games.

- [x] Yes, lets do it !
- [ ] No, i have no dreams and also don't want to be part of great things.
- [ ] Hmm, yeah ... maybe, but like Emily Howard said: I´m a lady !

**Comment by MrAmos123** [comment]
Mandatory anti-cheat client requirement would kill IW4x community servers player-base unless all IW4x server communities opted into this client download requirement. 

I think this would be best aimed at https://github.com/XLabsProject/iw4x-client rather than IW4MAdmin as this is a tool for moderation, more than an anti-cheat client.

**Comment by ChxseH** [comment]
Seems to just be a garbage spam issue, which is frankly useless here as this references cod4x only, and not IW4MAdmin as a whole.
