### ISSUE TITLE
Detect the game mode of each server

### ISSUE THREAD

**Issue by Chenterito** [RaidMax/IW4M-Admin#204]
What the title says, in my opinion it would be useful to identify what game mode the server is in when it deals with various game modes such as iw5 in my case.  Currently only identifies the map that the serividor is on.

**Comment by RaidMax** [comment]
I’m not really certain what you’re referring to. You mean the gametype, like tdm, ffa etc? If so that’s already done

**Comment by Chenterito** [comment]
Yes, that's what I was referring to .. well in my case I don't know where it is and that is not appreciated on the website.  just the map and server name
![Screenshot_20210428-075231_Chrome](https://user-images.githubusercontent.com/64875738/116407162-17069480-a7f7-11eb-9de7-d62b0ff8a12f.jpg)

**Comment by RaidMax** [comment]
Trying to figure out how this would look. The main issue I’m envisioned is newer cods don’t really easily expose the game mode. I currently track it with the g_gametype dvar, but it won’t be universal for every game

**Comment by RaidMax** [comment]
For games that support it, added functionality in 57f1dd3f3cd6b55c07fdc86a2c259e4e6ae1204c
Note it's currently not using any type of game string lookup so it'll be something like Rust - WAR

**Comment by Chenterito** [comment]
Thanks, it works now. Although I was wondering if it is possible to customize the type of game that is displayed on the web.
Example:
"WAR" showing "Team Match". Do it by defining this in the main configuration file, just as you do with the names of the maps.

**Comment by RaidMax** [comment]
That's the plan as a fast follow. Unfortunately each game can potentially have a different name for the game type. And Having something like `Wasteland- Global Thermo Nuclear War` might get kind of messy. So I haven't decided how I want to handle it yet, but I will update this issue with any  changes
