### ISSUE TITLE
Plugin VPN Detection wrongly kicking players

### ISSUE THREAD

**Issue by ju57** [RaidMax/IW4M-Admin#209]
Hello,
Recently I installed Plutonium T6 MP and I'm having issues on connecting to most of the servers. I started searching online, so I could troubleshoot this but I couldn't find much information about this topic. Basicly, whenever I try to connect into most of the servers, I connect and few seconds after I get kicked because of the VPN Detection plugin. 
Below there's a screenshot of the message I receive when I get kicked.
![Plutonium Screenshot 2021 06 07 - 20 36 30 41](https://user-images.githubusercontent.com/85518879/121077851-0f5fe580-c7d0-11eb-8be5-112088d7b659.png)
 
And if you're wondering, no I'm not using any VPN while playing.

Best regards,
just

**Comment by xerxes-at** [comment]
As seen in #195 you will have to get in contact with @xDefcon as the public version of the plug-in uses his VPN detection service.

**Comment by RaidMax** [comment]
Unfortunately as @xerxes-at pointed you would need to either reach out to the API maintainer, or contact the individual server owners to get whitelisted.

Closing there as there is nothing on my end I can do.
