### ISSUE TITLE
Command !killplayer

### ISSUE THREAD

**Issue by Chenterito** [RaidMax/IW4M-Admin#211]
This command does not work on iw5 plutonium. I use it correctly with the player's name, I don't get any errors. But the player does not die.

**Comment by RaidMax** [comment]
It's an IW4  only command. https://github.com/RaidMax/IW4M-Admin/blob/master/Plugins/IW4ScriptCommands/Commands/KillPlayerCommand.cs
`IW4ScriptCommands`
It requires mod integration and is more of an example command for users wanting to integrate with a game.
I do need to update it to only have IW4 as the supported game, but I made the command before I had game specific commands.
