### ISSUE TITLE
No !owner command 

### ISSUE THREAD

**Issue by Rush-er** [RaidMax/IW4M-Admin#212]
Hello,
i tried to run the server with IW4M admin but there is no interaction with the commands.

After the login the command !owner doesn't works.

Also there is no text reported on the webclient history for my user.

**Comment by Rush-er** [comment]
The game is Teknomw3
IW4M-Admin version: stable & beta both tested

**Comment by INSANEMODE** [comment]
Sounds like your game log isn't being read.
https://github.com/RaidMax/IW4M-Admin/wiki/FAQ#commands-not-responding

**Comment by Rush-er** [comment]
Thanks @INSANEMODE this solved the issue
