### ISSUE TITLE
EnableImplicitAccountLinking to True generating database errors

### ISSUE THREAD

**Issue by projectcpl** [RaidMax/IW4M-Admin#217]
Setting **"EnableImplicitAccountLinking": true,** generates database errors when trying to view player profiles on the web front. Full description in picture below.

![issue](https://user-images.githubusercontent.com/69830207/135380349-f20051e0-56af-42d8-8531-ac85629c300e.png)

**Comment by RaidMax** [comment]
I actually addressed this last week but haven’t put out a release yet because I was waiting for more changes, but seems I don’t have any in store at the moment so I will push out the update tomorrow

**Comment by RaidMax** [comment]
Resolved with 
aaf81f0
