### ISSUE TITLE
[QUESTION] VPN Exemptions

### ISSUE THREAD

**Issue by MrAmos123** [RaidMax/IW4M-Admin#22]
Is/can there be/a way to exempt me from VPN kicking. I use a VPN daily so it'd seem stupid to disable it just for this and on my server. 

My server is getting rather popular now so I'd like to exempt myself from VPN kicking, can you do it 'per-rank/id/name'?

For example, Moderator+ don't get kicked for enabled VPN's.

**Comment by MrAmos123** [comment]
Thanks very much!

**Comment by MrAmos123** [comment]
Reopening as I think this is broken with new xDevcon commit.

!whoami results in ID @5.
```
  "EnableClientVPNs": false,
  "IPHubAPIKey": null,
  "VpnExceptionIds": [ 5 ],
```

Maybe I'm doing the formatting wrong, but please can you point me in the right direction on how to use xDevcon's API for VPN kicking as it's still kicking me with above config.

**Comment by RaidMax** [comment]
See: https://github.com/RaidMax/IW4M-Admin/issues/25#issuecomment-416202420
