### ISSUE TITLE
optimize the !mapandgametype command

### ISSUE THREAD

**Issue by Chenterito** [RaidMax/IW4M-Admin#223]
I think it should interact with the filesystem, since the default names are not always used in "dsr" files in the case of iw5.  in my case I use a "dsr" called tdmmaniacos.dsr and that would not allow the execution of the command as it has been implemented.
interacting, when looking in the respective folder for the dsr file to be executed.
![20211128_192937](https://user-images.githubusercontent.com/64875738/143792730-c17da6d8-1a51-40a2-ab4e-84727d522c97.jpg)

**Comment by RaidMax** [comment]
IW4MAdmin will not be interacting with the file system for game specific implementation. My understanding is that you can’t load gametypes without a dsr on iw5.

**Comment by Chenterito** [comment]
Exactly, the "dsr" is the one in charge of establishing the type of game and the different options for it.  and on the other hand, if you directly execute the command "load_dsr namedsr" when not found in the defaults, it would be fine.

**Comment by RaidMax** [comment]
Yep that’s how it should be implemented currently. So I’m a bit unsure what the issue is.

If you do `!mag dome dd` it’ll do `load_dsr DD_default`, if you do `!mag dome custom` it’ll do `load_dsr custom`

Isn’t that what we want?

**Comment by Chenterito** [comment]
in theory that is correct. I'll try it

**Comment by Chenterito** [comment]
I tried it and it doesn't work properly.
The command does not change the map, it only sets a DSR to then manually apply `!map` dome and there it works only if a default name is used, such as:
`!mag dome tdm` -> There it works setting the correct dsr, but I have to use a `!map dome` for the map to change.
The other case. if I use `!mag dome DOMM.dsr` or `!mag dome DOMM` this doesn't work and it doesn't assign a correct DSR and the rest won't work either.
I hope I have explained myself.

**Comment by Chenterito** [comment]
`  $"load_dsr {(hasMatchingGametype ? gametype.ToUpper() + "_default" : gametype)};map {map}");`
I don't know about this language, but I think the error is in the formation of the concatenated command. because I used the same idea from my client console and if it works.
Like this: `load_dsr DOMM; map mp_dome`
I think the string is wrongly concatenated.

**Comment by RaidMax** [comment]
`!mag dome dom`

![image](https://user-images.githubusercontent.com/6732771/143799742-3396ce81-8792-4d8c-ba59-08e64d6e5ad8.png)

`!mag dom domm`

![image](https://user-images.githubusercontent.com/6732771/143799836-87520531-cce2-4f21-93a8-e0d84e2601ab.png)

I don't see where there is an issue with concatenation.

**Comment by Chenterito** [comment]
![image](https://user-images.githubusercontent.com/64875738/143800261-eea918a0-5195-4790-9bde-c32368873c5a.png)
It's what the server console shows when I run the command.

**Comment by RaidMax** [comment]
After testing locally I can confirm this issue is caused by Pluto IW5 not properly parsing multiple commands via rcon.
Updated 29ae00562159204b2ae485bb38af61c2bb97d45b to use separate commands. Will close once you can verify functionality as expected.

**Comment by Chenterito** [comment]
Now it works great
