### ISSUE TITLE
Error when executing on Linux

### ISSUE THREAD

**Issue by SwitChBlaDe343** [RaidMax/IW4M-Admin#224]
I recently got into Linux and decided to host a Pluto IW5 server, but after running the commands from the guide I get stuck with the error "Fatal error during initialization. An item with the same key has already been added. Key: 1" I've tried deleting the whole folder and trying again, but I get the same error. I've also tried it with multiple pre-release and stable versions all giving the same error. I'm not sure what's up. Maybe you can help me. 
![image](https://user-images.githubusercontent.com/31190698/147618572-2e68ec74-bc30-4937-9754-fb66dffcc1b3.png)

**Comment by RaidMax** [comment]
Had another user encounter this issue. It’s most likely due to your server not being configured correctly. Possibly a map not loaded or server not initialized properly. 

It’s not a problem with IW4MAdmin but rather an issue with the info response that Pluto IW5 is returning.

A temporary work around can be achieved by adding the following line to ParserPIW5.js

`  rconParser.Configuration.CommandPrefixes.RConGetInfo = undefined;`

**Comment by SwitChBlaDe343** [comment]
I seem to have fixed the problem regarding "Key:1", but now I have a new problem. 

Is there a way to manually point to the game log in the configuration file? I think it's because the server is running through wine, so the path is different than on windows.

**Comment by SwitChBlaDe343** [comment]
I mean when the plutonium-bootstrapper was initially created during the setup it had to run through wine, and as such created a strange path that IW4MAdmin can't find

**Comment by SwitChBlaDe343** [comment]
@RaidMax I think my only problem now is pointing to the log file, because i managed to get both the server and IW4MAdmin up and running, but the cmd's ingame don't work, indicating a log file read problem, if I'm correct

**Comment by RaidMax** [comment]
IW4MAdmin should automatically find the log path of your server even on Linux if you’ve set up the game server correctly. IW5 provides pieces of the path and IW4MAdmin sets it up for Linux filesystem. What is the path IW4MAdmin is generating?

**Comment by SwitChBlaDe343** [comment]
It's not generating a path, that's the thing. It just says "null" I followed the guide on the plutonium forum exactly to set up the server. Under Configuration/Iw4MAdminSettings.json ManualLogPath, if I don't set it myself as "/root/.wine/drive_c/users/root/Local Settings/Application Data/Plutonium/storage/iw5/logs" IW4M will not start and give me and error that says "/users/root/LOCA~/APPL~/PLUT~/storage/iw5/logs/games_mp27090.log" does not exist.

> /root/.wine/drive_c/users/root/Local Settings/Application Data/Plutonium/storage/iw5/logs < This is where the server stores the log file.

**Comment by RaidMax** [comment]
Closing this as it's platform specific. In docker and some linux distros the game engine will not return the actual disk path. In that scenario a manual log path is required.
