### ISSUE TITLE
Could not get lastest IW4MAdmin version

### ISSUE THREAD

**Issue by MateoCignetti** [RaidMax/IW4M-Admin#227]
Just that, when I open IW4MAdmin it takes forever to start because it looks for an update before, and I guess it tries to contact a server but can't. I even tried disabling my firework (ufw) to no avail. I'm also on linux, if that helps.

Honestly if I could just disable that version check on startup, would also work for me as well, but I'm not sure if you can do that on the latest version.

Running UpdateIW4MAdmin.sh retrieves the latest version successfully, but IW4MAdmin does not. Also, trying a fresh install doesn't fix the problem as well. The problem started randomly one time I opened the verified version of IW4MAdmin, it used to work but after that time, it doesn't anymore.

**Comment by RaidMax** [comment]
Not sure what version you're using but there's a 15 second timeout for checking on the update. Which imo is not "forever".
See if you can access `http://api.raidmax.org:5000/` as that's the URL used for the master server. Ensure that's the value stored in `IW4MAdminSettings.json` too. You may need to see if there's some external firewall blocking traffic on that port.

**Comment by MateoCignetti** [comment]
My bad, it's not "forever", I definitely exaggerated. I cannot access http://api.raidmax.org:5000/, not even on my phone or another computer with Windows, tried changing the DNS and also nothing, but I tried with a VPN and it works. It sucks, but I guess it has something to do with my ISP. Thanks for the blazingly fast response, you can close the issue as I don't think this can be resolved.

**Comment by RaidMax** [comment]
Thanks for the update. I’ll consider adding a flag at some point but as IW4MAdmin is designed to be run for extended periods, the occasional restart doesn’t warrant a huge priority at the moment.

**Comment by MRsoloPG** [comment]
hello i am having a probleme with my iw4madmin i am getting this error Could not get the dvar value for version
