### ISSUE TITLE
Ubuntu support ?

### ISSUE THREAD

**Issue by nysso** [RaidMax/IW4M-Admin#23]
I have a iw4x server on a VPS running **ubuntu 18.04**
is there a way to setup IW4M-Admin on it ? please guide me

**Comment by RaidMax** [comment]
Setup is documented in the readme: https://github.com/RaidMax/IW4M-Admin/blob/2.1/README.md
Linux is supported in the pre-release build: https://raidmax.org/IW4MAdmin/
Install .NET Core following these instructions: https://www.microsoft.com/net/download/linux-package-manager/ubuntu18-04/runtime-2.1.3

**Comment by MrAmos123** [comment]
@nysso 

```
wget -q https://packages.microsoft.com/config/ubuntu/18.04/packages-microsoft-prod.deb
sudo dpkg -i packages-microsoft-prod.deb
sudo apt-get install apt-transport-https unzip
sudo apt-get update
sudo apt-get install aspnetcore-runtime-2.1
wget https://raidmax.org/IW4MAdmin/Download/IW4MAdmin-2.2-prerelease4.zip
unzip IW4MAdmin-2.2-prerelease4.zip
mv StartIW4MAdmin.cmd start.sh
chmod +x start.sh
screen -S IW4MAdmin -d -m sh start,sh 
```
