### ISSUE TITLE
[Webfront] Search player option on Top Players section

### ISSUE THREAD

**Issue by DanielVou** [RaidMax/IW4M-Admin#24]
One feature you should add for IW4M Admin is a search option on top players page, because for example I don't know what position I am on it.

And on profile page you should add the player position on the same side as the status or player name.
![profile page](https://user-images.githubusercontent.com/42682615/44606081-36390280-a7c2-11e8-9bda-40284acd54be.png)

**Comment by RaidMax** [comment]
There does seem to an odd bug related to the minimum time played to show up on stats. I’ll look into it today

**Comment by RaidMax** [comment]
Turns out it wasn't an issue with the minimum time, but rather the time played wasn't being incremented properly on disconnect due to the change of how player states were handled. Will be addressed in the next commit

**Comment by RaidMax** [comment]
closing this, as I'm not planning on doing searching on top stats this release. Only the profile #
