### ISSUE TITLE
Change games_mp.log location

### ISSUE THREAD

**Issue by abhiiously** [RaidMax/IW4M-Admin#244]
I run iw4x in a docker and I was wondering if theres a way to change where IW4MAdmin looks for the games_mp.log file? It currently sits in \iw4x\userraw\logs

**Comment by Ayymoss** [comment]
In the `IW4MAdminSettings.json` file there's an option within the `Servers` configuration for `"ManualLogPath": "/your/path/here.log",`.

**Comment by RaidMax** [comment]
Be aware that by default docker doesn’t allow cross container file access unless you are using shared folders.

**Comment by Ayymoss** [comment]
Please re-open this ticket if you have any questions or join the IW4MAdmin Discord. https://discord.gg/AKVGU5B
