### ISSUE TITLE
IW6X no games_mp-.log File

### ISSUE THREAD

**Issue by Mario07081975** [RaidMax/IW4M-Admin#245]
hi Guys.
how can i use iw4madmin for ghost?
Ghost itself does not create a games_mp.log file

Tried this one, but it crashed the server :https://github.com/Joelrau/S1x-IW6x-g_log-script

**Comment by RaidMax** [comment]
This was the recommended solution. If the server is crashing that would be an issue with the client. Closing this unless you have an IW4MAdmin specific issue.
