### ISSUE TITLE
IW4Admin commands not working in game on T5

### ISSUE THREAD

**Issue by MilitantAtheist2** [RaidMax/IW4M-Admin#249]
Hello I've been trying to get the commands working now for a while on my T5 server. Commands won't work when I enter and try to use !owner to claim ownership of the server. Every else is fine and the IW4m Admin console says now monitoring your server when I run it. Messages are displaying fine on entry to the server and while playing in it. Is there a way to set an owner manually through a config file? 

I can upload screenshots if need be, thanks.

**Comment by RaidMax** [comment]
Please join the [discord](https://discord.gg/yNPxpFTq)  to view the resources related to this. It's not an issue with IW4MAdmin but rather there are some hoops to get T5 to properly log out to a file. Closing this as not an IW4MAdmin issue.
