### ISSUE TITLE
[Suggestion] Add Proxy/VPN detection from xDefcon

### ISSUE THREAD

**Issue by MrAmos123** [RaidMax/IW4M-Admin#25]
Website: https://www.xdefcon.com/ 

API: https://api.xdefcon.com/proxy/check/?ip=
Example (VPN): https://api.xdefcon.com/proxy/check/?ip=196.52.84.36
Example (No VPN): https://api.xdefcon.com/proxy/check/?ip=80.60.16.43

Doesn't have a poll limit, which is why I think you should change it from IPHub to xDefcon as £9.99 for 10,000/reqs a day is overly expensive on IPHub, and this alternative is free. (or IPHub's 1,000/reqs a day for free users.)

Instead of change it, maybe add this as an optional choice, so the server owner is able to switch between IPHub (if they have an existing subscription) to xDefcon.

**Comment by RaidMax** [comment]
I think this is a good idea, however with the JavaScript plugin support, I think I can extract the VPN detection support out into a plugin that can be freely modified to use any arbitrary VPN detection service

**Comment by RaidMax** [comment]
I've pushed pre-release 5. The VPN detection has been moved to a script plugin, see: https://github.com/RaidMax/IW4M-Admin/blob/master/Plugins/ScriptPlugins/VPNDetection.js

**Comment by MrAmos123** [comment]
You work fast. Damn. Thanks very much!

**Comment by MrAmos123** [comment]
@RaidMax Can you quickly explain how to use the new xDevcon's API instead of IPHub?

```
Enable client VPNs? [y/n]: n
Enter iphub.info api key: g
  "EnableClientVPNs": false,
  "IPHubAPIKey": "g",
  "VpnExceptionIds": [],
```
How do I alternate between IPHub and xDevcon?

As of right now, I believe I'm using IPHub?
If I was to remove 'g' from the API key would it automatically switch to xDevcon?

**Comment by RaidMax** [comment]
As of now I’ve removed the IPHub VPN checking and switched to defcon. To add exemptions modify plugins/VPNDetection.js

I can confirm it’s working properly on my server.

**Comment by MrAmos123** [comment]
Confirmed working.
