### ISSUE TITLE
T5 Zombies Version

### ISSUE THREAD

**Issue by Nuklez16** [RaidMax/IW4M-Admin#250]
Attempting to boot IW4MAdmin
shows below error

<img width="503" alt="image" src="https://user-images.githubusercontent.com/18061996/172985827-ce7ed5e6-1869-484d-805a-a696c8bfa108.png">

Copy of IW4MAdmin Settings attached below

**Comment by RaidMax** [comment]
T5 SP/ZM does not have RCon support yet and as such IW4MAdmin is not compatible.

Closing this as only MP is supported.
