### ISSUE TITLE
Support JS ES6 for plugin development

### ISSUE THREAD

**Issue by vdawg-git** [RaidMax/IW4M-Admin#255]
It is kinda hard to write es5 code for me, as I have never done that before.
And ESLint does not support ECMA 5.1. Using a bundler which converts the code would also not work as the `var plugin` would probably get changed.

**Comment by RaidMax** [comment]
I have neither the time nor motivation to create my own JavaScript engine.

As such IW4MAdmin utilizes [Jint](https://github.com/sebastienros/jint) for JavaScript parsing. You can view the readme of that project to see what is and isn’t supported. I’m using a relatively recent build so it should have the majority of listed features.

You can also view https://github.com/RaidMax/IW4M-Admin/blob/release/pre/Plugins/ScriptPlugins/SubnetBan.js#L1 for additional plugin sample utilizing newer JavaScript syntax.

**Comment by vdawg-git** [comment]
Understandable and thank you for the info
