### ISSUE TITLE
sv_sayName does not work in H1

### ISSUE THREAD

**Issue by Chenterito** [RaidMax/IW4M-Admin#256]
"sv_sayName" does not work with IW4MAdmin. I was doing tests and from the h1-Mod console it works.
With IW4MAdmin
![unknown](https://user-images.githubusercontent.com/64875738/183225246-745f9270-8ad5-4d93-af4c-74d5eda9000f.png)
Say in console
![IMG_20220805_190644](https://user-images.githubusercontent.com/64875738/183225321-fb19dc9b-a737-47cb-8d67-041152fa2824.png)

**Comment by RaidMax** [comment]
H1 parser, which was not provided by me, uses the `sayraw` and `tellraw` commands to print chat. Those commands do not honor the `sv_sayname` dvar. 

If you want to have the `sv_sayname` prefixed, modify the parser to use the `say` and `tell` commands.

eg:
```js
rconParser.Configuration.CommandPrefixes.Tell = 'tell {0} "{1}"';
rconParser.Configuration.CommandPrefixes.Say = 'say "{0}"';
```

**Comment by Chenterito** [comment]
changing that won't affect how iw4madmin works in the game ?  will give any error?

**Comment by Ayymoss** [comment]
No, it's how IW4MAdmin will issue commands to Rcon. Give it a go. You can always revert the change if something doesn't work as expected. :)

**Comment by Ayymoss** [comment]
Closing as solved.
