### ISSUE TITLE
GameLog issue when starting IW4MAdmin

### ISSUE THREAD

**Issue by Lucas6635** [RaidMax/IW4M-Admin#258]
I can't find the StartIW4MAdmi.cmd file in the latest version

**Comment by INSANEMODE** [comment]
Just downloaded the latest pre-release zip, and it is there. What version are you downloading?

**Comment by Lucas6635** [comment]
https://github.com/RaidMax/IW4M-Admin/releases the first of the

**Comment by Lucas6635** [comment]
![erreur](https://user-images.githubusercontent.com/99401948/185901142-56c4b613-01b0-4363-bcb4-10778bfc77ec.PNG)
and i have this error

**Comment by Lucas6635** [comment]
in fact I have a host but I do not know if plays
