### ISSUE TITLE
JAMstack with Svelte

### ISSUE THREAD

**Issue by vdawg-git** [RaidMax/IW4M-Admin#260]
I would be interested in developing the front-end app for IW4Admin with Svelte.
I am not sure though if this would help you a lot and how much time it would cost you to create the APIs for that.

Does this sound good to you?

**Comment by RaidMax** [comment]
I’m not quite sure the purpose of this. IW4MAdmin already has a web interface that  works well and has no performance issues and is built for desktop and mobile in mind. 

I have plans to migrate to a more browser focused approach in the future but would most likely go with Blazor.

**Comment by vdawg-git** [comment]
Makes sense, I just liked the idea of being able to tinker with it :)
