### ISSUE TITLE
[Failed to initialize] Could not get the dvar value for sv_running

### ISSUE THREAD

**Issue by Pendrag00n** [RaidMax/IW4M-Admin#264]
Honestly I have no idea what a dvar is or what is causing this problem since I couldn't find any issues related to this one, I believe everything is set up correctly but I haven't done this before so I don't know for sure :(

![image](https://user-images.githubusercontent.com/88731722/188277333-7d05c437-037b-40d3-9785-4c0229b17b72.png)

**Comment by RaidMax** [comment]
This is a configuration issue. Please consult the FAQ https://github.com/RaidMax/IW4M-Admin/wiki/FAQ#common-issues and only after you’ve thoroughly read and attempted the suggestions and still have a problem you can join the discord and request support. 

GitHub issues are for actual defects.

**Comment by Pendrag00n** [comment]
Fixed. Even though I remember selecting the BO2 parser, `Call of Duty` was written instead of `Plutonium T6 Parser` thanks anyways and sorry for directly jumping onto github for an answer

**Comment by Ayymoss** [comment]
@Pendrag00n https://discord.gg/kGKusEzUJp Join the IW4MAdmin Discord for future support related questions.
