### ISSUE TITLE
Penalty list  - Players who received penalty colour coded 

### ISSUE THREAD

**Issue by vdawg-git** [RaidMax/IW4M-Admin#265]
Currently players who for example got reported in the Penalty List always show up as blue, even if they are banned or flagged:

<img width="611" alt="image" src="https://user-images.githubusercontent.com/28539403/191196290-cde2bedf-c86d-4c05-853e-701a9540510c.png">

So, often when checking out the reported players profile, they are already banned by the anti-cheat system.
Or if you banned them subsequently, you need to remember their name when scrolling through a long list of reports as their name colour does not change.
Colour coding those names would be a nice UX improvement:
<img width="654" alt="image" src="https://user-images.githubusercontent.com/28539403/191196714-010eb25e-640d-4155-b7c9-a392f28c16eb.png">

**Comment by RaidMax** [comment]
implemented in [4cf62b7](https://github.com/RaidMax/IW4M-Admin/pull/268/commits/4cf62b73f1a04edce3c82db1579cab60ced2ba31)
