### ISSUE TITLE
Cheat Suspicion Score

### ISSUE THREAD

**Issue by vdawg-git** [RaidMax/IW4M-Admin#266]
When banning players based on reports I realized that I am always doing the following:
- Checking out how many people reported them
- Checking how many reports they received and over which time-frame. (A lot of reports within 1 year or a lot of reports within one week)
- Checking their play time (is it just one hour, or even 3 weeks)
- Checking if an anti-cheat metric is unusually high
- Checking whom reported them. Did they have a lot of play time, or is just from someone with 40min play time.

- Then I decide about the result:
    - If they received *a lot* of reports within a short period of time while not having a lot of play time (lets say not even a week), they get banned
    - If they received just a couple of reports but have only played a couple of hours or even minutes they get banned
    - If they have a lot of reports in general, but scattered around a large time-frame while having played for a long time on the servers, they do not get a ban, - unless players with a lot of play time have reported them, too.

So I think a nice feature would be to have a metric which calculates something like a `Cheat Suspicion Score`, based on for example those factors, which then gets displayed on their profile.
Then, in reference to #265 , their names can be colour coded on a scale between lets say whiteish yellow to deep reddish orange with strike-through red for the banned players.
<img width="651" alt="image" src="https://user-images.githubusercontent.com/28539403/191203553-218fb3f0-dd53-44ba-9289-9f4d8ae823a2.png">

And the cheat score could be displayed like this:
<img width="501" alt="image" src="https://user-images.githubusercontent.com/28539403/191204074-7ca9d144-2e5c-4113-ae44-5df248f20058.png">

**Comment by Ayymoss** [comment]
I like the cheat suspicion score idea 👍

**Comment by RaidMax** [comment]
This has been talked about and before and lots of thought has gone into it. 

The reality is we don’t have enough data to make any accurate predictions. 
It’s really just guessing and doesn’t provide reliable data. 

While I appreciate the idea, there would need to be a more provable set of metrics to back up the cheater score, which at this time just don’t exist.
