### ISSUE TITLE
[BUG] Can't access WebFront

### ISSUE THREAD

**Issue by MrAmos123** [RaidMax/IW4M-Admin#27]
http://51.15.140.59:1624/

```
  "EnableWebFront": true,
  "WebfrontBindUrl": "http://51.15.140.59:1624",

[08.27.2018 11:29:36.408] - Warning: Could not connect to heartbeat server - POST "http://api.raidmax.org:5000/authenticate" failed because response status code does not indicate success: 401 (UNAUTHORIZED).
```

The connection refused?

I'm unsure what logs I could provide to help, please let me know.

**Comment by MrAmos123** [comment]
Update, the plugin is running now but I can't see port 1624 listening. 
```
root@scw-8d0f64:~# netstat -ntlp | grep LISTEN
tcp        0      0 127.0.0.53:53           0.0.0.0:*               LISTEN      13800/systemd-resol
tcp        0      0 0.0.0.0:22              0.0.0.0:*               LISTEN      6080/sshd
tcp        0      0 127.0.0.1:8125          0.0.0.0:*               LISTEN      6764/netdata
tcp        0      0 0.0.0.0:19999           0.0.0.0:*               LISTEN      6764/netdata
tcp        0      0 0.0.0.0:28960           0.0.0.0:*               LISTEN      28225/iw4x.exe
tcp6       0      0 :::22                   :::*                    LISTEN      6080/sshd
tcp6       0      0 ::1:8125                :::*                    LISTEN      6764/netdata
tcp6       0      0 :::19999                :::*                    LISTEN      6764/netdata
root@scw-8d0f64:~#
```

**Comment by RaidMax** [comment]
Try re downloading pre release 5, I've updated two of the files. If it still fails to bind, it's one of the following issues:
1) Your NIC isn't actually assigned the IP you're trying to bind to (I would recommend using a domain and binding to that)
2) The port is already in use (make sure nothing else is listening on that port
3) You don't have permission to bind to port

**Comment by MrAmos123** [comment]
@RaidMax https://i.imgur.com/oslQBOq.png

```
401 - Unauthorized: Access is denied due to invalid credentials.
You do not have permission to view this directory or page using the credentials that you supplied.
```

**Comment by RaidMax** [comment]
Oops I forget when I update a zip folder it changes the permissions, I’ll make it accessible when I get to work

**Comment by RaidMax** [comment]
@MrAmos123 I've updated the permissions. Let me know if the issue still occurs.

**Comment by MrAmos123** [comment]
Resolved...

The resolution I used makes no sense to me:

Below didn't work:

```
  "WebfrontBindUrl": "http://127.0.0.1:1624",
  "WebfrontBindUrl": "http://51.15.140.59:1624",
```

Below worked...

`  "WebfrontBindUrl": "http://0.0.0.0:1624"`,

**Comment by Bluscream** [comment]
if that doesnt make sense to you you probably didnt watch out in admin class :P

Binding to 127.0.0.1 would mean only localhost can connect to that port. 0.0.0.0 just means every ipv4 can connect

**Comment by MrAmos123** [comment]
@Bluscream I get that, but what I don't get is why it wouldn't bind on the public IP but it would bind on 0.0.0.0?

**Comment by MrAmos123** [comment]
Understood, thanks anyways, as long as it's working, right? :)
