### ISSUE TITLE
Please add Zombie Stats

### ISSUE THREAD

**Issue by Energetixgamin** [RaidMax/IW4M-Admin#271]
Please add T6 Zombie Stats
- (Kills, Downs, revives, Alltime Score)
- Playtime

**Comment by Ayymoss** [comment]
I don't believe this is planned. 
Your requests may be possible through a plugin.

**Comment by RaidMax** [comment]
No Call of Duty zombies provides this data in the log file. It would have to be done through a mod for each CoD zombies game. Not planning on implementing this so it would have to be a community driven effort.

**Comment by Energetixgamin** [comment]
Pity for me
