### ISSUE TITLE
"Not monitoring server due to uncorrectable errors"

### ISSUE THREAD

**Issue by SingingQ** [RaidMax/IW4M-Admin#276]
Hosting environment: Production
Content root path: C:\Games\Bo2 New copy\pluto_t6_full_game\IW4M\Lib\..\
Now listening on: http://0.0.0.0:1624
IW4MAdmin is up to date
Performing important database migrations that may take some time... Do not close IW4MAdmin!
Migrations are complete!
Attempting to establish a connection with your server(s)...
Not monitoring server due to uncorrectable errors [(MyIP):4976]

**Comment by Ayymoss** [comment]
Please ask in Discord. 

https://discord.gg/ZZFK5p3
