### ISSUE TITLE
Wildcard for search by IP

### ISSUE THREAD

**Issue by vdawg-git** [RaidMax/IW4M-Admin#278]
We have a cheater who always comes back and I want to ban his new accounts.
Also I want to know if there are other players within his IP range playing on our servers for a potential IP range ban.

Currently though the ban management page does only allow the lookup for an exact  IP, not something like `44.44.*`

This would be a nice to have feature.

**Comment by RaidMax** [comment]
There is a wildcard search.
You can search by octet.

For example if you want to find a LAN address
`192.168.1.`

For your example use `44.44.`

There is a search overhaul coming out soonish that will make it more intuitive though

**Comment by Ayymoss** [comment]
Please find our Discord Support link for future questions. https://discord.gg/ZZFK5p3
