### ISSUE TITLE
Can anyone help me resolve this?

### ISSUE THREAD

**Issue by Arkadiumx** [RaidMax/IW4M-Admin#283]
Attempting to establish a connection with your server(s)...
Not monitoring server due to uncorrectable errors [24.115.52.120:28960]
[2023-03-18 12:04:09.233  FTL] Failed to initialize IW4MAdmin
SharedLibraryCore.Exceptions.NetworkException: Reached maximum retry attempts to send RCon data to server
      at IW4MAdmin.Application.ApplicationManager.InitializeServers()
      at IW4MAdmin.Application.ApplicationManager.Init()
      at IW4MAdmin.Application.Program.LaunchAsync(String[] args)
Fatal error during initialization
Reached maximum retry attempts to send RCon data to server
Press enter to exit...
Shutdown complete

**Comment by NotHGM** [comment]
https://github.com/RaidMax/IW4M-Admin/wiki/FAQ#could-not-communicate-with-ipport--reached-maximum-retry-attempts-to-send-rcon-data-to-server

**Comment by ghost** [comment]
Mind asking what game you trying to do?

**Comment by Ayymoss** [comment]
Issues are not the place for support. Please join the [discord ](https://discord.gg/ZZFK5p3)for support
