### ISSUE TITLE
Error when displaying servers

### ISSUE THREAD

**Issue by hennessy100kk** [RaidMax/IW4M-Admin#291]
Installation went fine and everything was working including the webfront fully. After a bit of editing basic settings and installing one plugin, suddenly the servers tab stopped working. Everytime I am met with this error message:
![error](https://user-images.githubusercontent.com/130660200/231740915-53759b8f-d175-4361-88a6-ab0463b059af.png)

Everything else works fine and has been tested. The server is alive and well. Heres what the console spits out:
[log.txt](https://github.com/RaidMax/IW4M-Admin/files/11221583/log.txt)

**Comment by Ayymoss** [comment]
Hi, are you in the IW4MAdmin Discord? https://discord.gg/ZZFK5p3

We can help you here a lot easier.

**Comment by Ayymoss** [comment]
Please continue on Discord if you need further help.
