### ISSUE TITLE
Critical server crash in Zombies/Origins

### ISSUE THREAD

**Issue by GewoonIraj** [RaidMax/IW4M-Admin#293]
When activating the Tank in Origins, the entire server fully crashes. 
Reason why I stated "critical" in the title, is because you need to use the Tank to gather all parts for the Lightning Staff (which also is needed for the Easter Egg).

**Comment by Ayymoss** [comment]
IW4MAdmin is an Administration tool for Call of Duty games. 
IW4MAdmin makes no changes to the game's source.

Please raise your issues with the relevant game's GitHub project.
