### ISSUE TITLE
[Suggestion] Make Top Players in Web-Front update dynamically.

### ISSUE THREAD

**Issue by MrAmos123** [RaidMax/IW4M-Admin#30]
I haven't restarted IW4M in about 2 days and it still has the top players from when I started IW4M then.

Can you make it refresh dynamically, or each time I press F5?

http://195.154.102.115:1624/Stats/TopPlayersAsync

**Comment by RaidMax** [comment]
It does. 
Either your criteria (time played) for top stats is too small (check `StatsPluginSettings.json`)
The version you're running isn't saving the stat history updates (most likely and it's fixed)
The players that are playing now aren't as good as the first players.
