### ISSUE TITLE
Not all Colors work

### ISSUE THREAD

**Issue by SladeGit** [RaidMax/IW4M-Admin#301]
Why is (Color::Orange) not work and (Color::Red) is Working?

Orange is not the only one not working, Gold...

**Comment by RaidMax** [comment]
Need more info. What game? Where are you trying to set the message?

**Comment by INSANEMODE** [comment]
I don't believe any game parser has a color mapping for "Orange", from a quick search.

**Comment by RaidMax** [comment]
Also this is the default supported colors cod engine  https://github.com/RaidMax/IW4M-Admin/blob/4002745ad74d8c5d5a878f1f16e7a7caa831f55b/Application/RConParsers/DynamicRConParserConfiguration.cs#LL41C14-L41C14

notice orange isn’t on there. Also ^: is iw4x specific

**Comment by SladeGit** [comment]
I use the latest pre version  

"AutoMessages": [
    "(Color::Orange)You see a cheater? Report him with (Color::White)!report NAME REASON!"
  ],

and

  "UserAnnouncementMessage": "(Color::White)Welcome {{ClientName}} on (Color::Orange)Snipys",
  "UserWelcomeMessage": "",
  "PrivilegedAnnouncementMessage": "(Color::Red){{ClientLevel}} (Color::White){{ClientName}} (Color::Orange)has joined the server"

Colors not working or what do i wrong? How can i solve it?
