### ISSUE TITLE
Hacker shuts down admin program every time he joins

### ISSUE THREAD

**Issue by KillerRose83** [RaidMax/IW4M-Admin#302]
I am a Senior Admin for V3X Gaming Inc. We have 10 servers that all run IW4M-Admin, whenever this hacker joins it causes a plugin error within the IW4M console we have tried to ban this person but he makes it back on other accounts/pc hardware etc.

The only thing I can really give you is the logs for it.

**Comment by RaidMax** [comment]
Please join the iw4madmin discord and provide the logs

**Comment by RaidMax** [comment]
Discussed via dm, most likely related a custom plugin
