### ISSUE TITLE
Scraping user IPs by abusing IP wildcard search 

### ISSUE THREAD

**Issue by v938471** [RaidMax/IW4M-Admin#310]
Unsure if server owners care about this but there's a trivial way to extract the IP (or all linked IPs) of any user who has connected to a server with a webfront by abusing the search-by-IP wildcard function. I've linked a gist of a short python script to demonstrate how it works - anyone who runs it can find the IP of a given user with at most 120 requests to the webfront (perhaps this can be optimized further but I haven't bothered) - the script visits namelessnoobs, but you can test whatever site you want by changing the value of the "base_url" variable. Could be prevented by requiring authorization for such searches or server owners enforcing rate-limits. 

https://gist.github.com/v938471/6a403c890457d142b6be5e690db400b2

(worthy to note that this is only particularly "bad" for newcomers as they won't have a number of ip addresses linked to their account, finding *all* ips linked to some account will take considerably more requests)

**Comment by RaidMax** [comment]
Addressed in[c41081b](https://github.com/RaidMax/IW4M-Admin/commit/c41081bdb101cdf0eb0a7cc100fc23d22f29376c)
Thanks for reporting.
