### ISSUE TITLE
I would like to Dockerize it

### ISSUE THREAD

**Issue by fabri2000779** [RaidMax/IW4M-Admin#313]
Hello, sorry to boether you. Im trying to dockerize your app since i want to put it in k8s, i know i know im crazy hahahahaha

But i just would like to know how you store the server configuration, i saw when you first run this it ask you for some details like de cod, etc and im thinking how to bypass this promp because to build the image will be a problem. I can look for a workaround for sure.

Far i saw you cannot pass args to the script something like --no-interactive. so that is why im asking how you saw with data, if you save it as a json then it will be easy for me but again im not sure how you do it.

I will appreciate any help you can give me related to this :)

**Comment by RaidMax** [comment]
The setup configuration is stored in `Configuration/IW4MAdminSettings.json`. If that file is present and valid it will not prompt for user input. There are also some other configs that may need to be present as well. After the first successfully setup run all the required configs will be populated in that folder.

**Comment by fabri2000779** [comment]
that was fast. Thanks you i appreciate it alot, this help me alot :)

feel free to close this
