### ISSUE TITLE
T7x (BOIII) server can't connect

### ISSUE THREAD

**Issue by anlekg** [RaidMax/IW4M-Admin#317]
Hi there, i'm trying to monitor my servers through IW4M, no issue on Plutonium ones but i'm having trouble with T7.

I'm using BOIII config, so first i used "BOIII Parser" on my config, but IW4M was giving me the "Dvar version" error.
So I swapped to Black Ops 3 Parser, and now i'm getting the "Max RCON attempt" error.
I checked Rcon_password, net_port, log path, nothing seems wrong.

Also when IW4M tries to reach my server i get this log on my console : 
![image](https://github.com/RaidMax/IW4M-Admin/assets/106981899/1f7678ce-b055-4faf-a291-0fbefef63af3)

Any ideas ? Thanks a lot

**Comment by diamante0018** [comment]
You failed to do something correctly. Everyone who is using T7x (not the original boiii as that client had an issue with IW4m) can run IW4M.

See the F.A.Q. https://github.com/RaidMax/IW4M-Admin/wiki/FAQ#could-not-get-the-dvar-value-for-version

**Comment by anlekg** [comment]
Ok I may have misstyped the title.... i'm actually using the boiii client, as i saw "BOIII Parser" on the config.
Shall I swap to T7x ? Do you have a link for that client ?

**Comment by diamante0018** [comment]
master.bo3.eu/t7x/t7x.exe

**Comment by diamante0018** [comment]
However, looking again at what you posted, switching clients is not gonna solve your problem
T7x contains fixes to the status ever BOIII doesn't have. Your issue stems from something else.
You didn't setup IW4M correctly still.
See the FAQ

**Comment by anlekg** [comment]
Hi, thanks for your answer.
I built the exe from alterware repo, switch the conf back to BOIII Parser and it worked.
Thanks for the help !
