### ISSUE TITLE
how to renable webfront

### ISSUE THREAD

**Issue by tiger710c** [RaidMax/IW4M-Admin#322]
hi i was going through the tut and didnt turn on webfront until i realized how important it is there a way that i can enable it now?

**Comment by Ayymoss** [comment]
@tiger710c Please can you join the Discord if you have any further issues as it's easier to support there. https://discord.gg/ZZFK5p3

However, if you've accidentally disabled it, if you check `Configuration\IW4MAdminSettings.json` towards the top you should see `"EnableWebFront":`, setting this to true should resolve it, assuming it's not some other underlying problem.
