### ISSUE TITLE
Overlapping text

### ISSUE THREAD

**Issue by dellmas** [RaidMax/IW4M-Admin#323]
I run this on h1-mod servers, and it works great, Really sweet features. 

It occasionally overlaps some game text and I'm wondering if there is a way I can lower it's text position a little? I've looked through a lot of the configs and dont see any settings for it's current position. Thanks.

**Comment by Ayymoss** [comment]
It would be very helpful if you provided screenshots of this overlapping text. There's a lot of text in IW4MAdmin.

**Comment by RaidMax** [comment]
I’m pretty certain this is related to the game itself. Perhaps there is a client dvar to adjust chat position like on older cods . Eg `cg_chatheight`

**Comment by dellmas** [comment]
![image](https://github.com/RaidMax/IW4M-Admin/assets/85115737/5dfa5fca-d664-4741-b618-7b0610b80031)

**Comment by dellmas** [comment]
![image](https://github.com/RaidMax/IW4M-Admin/assets/85115737/c775e270-22e4-403f-b90b-5460d701b52e)

**Comment by diamante0018** [comment]
Yep, this has nothing to do with IW4M
