### ISSUE TITLE
Ban appeal Ascension on Cavern server

### ISSUE THREAD

**Issue by x1no1412** [RaidMax/IW4M-Admin#327]
Hello, I would like to request an unban because I didn't realize that pressing the nuke button once constitutes nuke abuse. I thought using the nuke one time was not considered abuse, but that was my mistake, and I won't use the nuke again.
https://steamcommunity.com/profiles/76561198250075922/  greetings ascension

**Comment by Ayymoss** [comment]
IW4MAdmin is an administration tool for other community hosters to run. You'll need to contact that community and request to unban.

We cannot unban you.

**Comment by x1no1412** [comment]
Do you know which platforms host communities

**Comment by diamante0018** [comment]
> Do you know which platforms host communities

https://forum.alterware.dev
https://forum.plutonium.pw
https://auroramod.dev
