### ISSUE TITLE
commands not working

### ISSUE THREAD

**Issue by mhamzaali1** [RaidMax/IW4M-Admin#328]
I have configures IW4M admin for cod4x. when i try to take owner control by !owner typed in game chat, it does not work. other command also not work.

**Comment by Ayymoss** [comment]
@mhamzaali1 Please join Discord for help. But please, you're already on GitHub, consider looking through the Wiki for FAQ. This is one of the most asked problems. 

https://github.com/RaidMax/IW4M-Admin/wiki/FAQ#commands-not-responding

https://discord.gg/ZZFK5p3
