### ISSUE TITLE
[!BUG!] NBSClan Admin Panel Client ID 0! (Anyone has IW4MAdmin user ID on your Panel)

### ISSUE THREAD

**Issue by MrAmos123** [RaidMax/IW4M-Admin#33]
I don't know why... But I checked your Admin Panel to see if you had banned this guy I think may be cheating on my server lol...

But, I noticed I could see their IP's, which is a no-go, dropped down the user tab and low-and-behold, my apparent 'Client Profile' ID is @1.

https://i.imgur.com/MewY3yI.png - Profile Proof
https://i.imgur.com/mMSDVHv.jpg - I promoted myself
https://i.imgur.com/UH7NfYF.png - Command List proof. (With console)
https://nbsclan.org/Client/PrivilegedAsync - You can see me here. Fz Amos.

I haven't done anything other than promote myself to test, please check the logs if you're uneasy about this, which would be understandable. I have left my rank as Senior Admin so you can check yourself, however, please feel free to remove my rank entirely... 

Plus, I can't really play on your servers due to latency as I'm from UK. 

I'm just trying to disclose this, obviously, I don't need to tell you what to do, but if people are browsing your issues page actively they can also do what they hell they'd like so I hope you have a backup! 

I apologise in advance if you would have liked me to disclose this in a more private matter.

@RaidMax for pinging.

**Comment by RaidMax** [comment]
Closing as it was just a reverse proxy issue, not a code issue.
