### ISSUE TITLE
Regex issue - H2M

### ISSUE THREAD

**Issue by mgejay** [RaidMax/IW4M-Admin#339]
Any possibility we can get a commit to fix the regex errors for H2M?

**Comment by Ayymoss** [comment]
Feel free to submit it, be sure not to break working instances. 

There's no maintained client, so which community member's client do you expect us to fix without breaking others?

**Comment by RaidMax** [comment]
The underlying issue is a bug in the h2m code, so really any “fix” would be a bandaid.

**Comment by mgejay** [comment]
> The underlying issue is a bug in the h2m code, so really any “fix” would be a bandaid.

Didn't know this was formatting issues on their side. Will definitely bring it to their attention.

**Comment by mgejay** [comment]
Closed, not an IW4M issue.
