### ISSUE TITLE
[Info Request] Explanation of Profile Statistics

### ISSUE THREAD

**Issue by MrAmos123** [RaidMax/IW4M-Admin#34]
When you get some time please can you explain the statistics values in ReadMe file?
```
757.88 Performance
0.0519° Hit Offset Average
0.071 Max Strain
```
Specifically the above values I think need explaining.

**Comment by RaidMax** [comment]
Performance is Average of Skill + Elo Rating
Skill is an number derived from an algorithmic processing of a player's Kill Death Ratio (KDR) and Score per Minute (SPM).
Elo Rating is based off of the number of encounters a player wins.

The other two values are anti-cheat related statistics that I will divulge eventually.

**Comment by RaidMax** [comment]
Discussed via DM
