### ISSUE TITLE
I need help with the unique ID

### ISSUE THREAD

**Issue by Yosmay8** [RaidMax/IW4M-Admin#349]
I need you to help me so that the players on my servers always maintain a united ID, because when I run IW4admin when I enter the room it tells me a welcome message that I have entered the room for the first time and that is not the case, I have played in that room more than 5 times and when I look in the Iw4admin log folder my ID is not the same, that happens every time I enter and leave the room the ID changes, I need a solution for this, thank you, my server does not It's on the internet, it's here in my houses for the people of the neighborhood on the Lan.

**Comment by Ayymoss** [comment]
You were already informed why this is not possible.

From RaidMax
> Sorry with decentralized clients or clients not using a master server there’s nothing we can do
