### ISSUE TITLE
[Webfront] User page ban menu changes concerning temporary bans

### ISSUE THREAD

**Issue by Mathsma** [RaidMax/IW4M-Admin#36]
Currently the ban menu on the user page only allows you to permanently ban a user. An option to temporarily ban a user should also be added to the pop-up menu using a drop down with preset durations, i.e. 1 hour, 6 hours, 1 day, 1 week, permanent.

You also cannot unban temporarily banned users through the user page lock icon. This should be changed to allow unbanning through the user page lock icon.

**Comment by RaidMax** [comment]
Added in https://github.com/RaidMax/IW4M-Admin/commit/bc0fe3daec7ba1995c9fac28ba69a4baff12818e
