### ISSUE TITLE
[Bug] Linked accounts allow inactive users to stay active on top stats

### ISSUE THREAD

**Issue by Mathsma** [RaidMax/IW4M-Admin#41]
Inactive accounts are set to expire and not appear on the top stats page after a set period of inactivity. However, if a user changes their GUID and stays active, their previous account will still be considered active and will not drop off, even after their last seen date passes the maximum allowed time of inactivity.

**Comment by RaidMax** [comment]
Turns out it's not actually that. See https://github.com/RaidMax/IW4M-Admin/issues/24#issuecomment-418153822
