### ISSUE TITLE
[Feature Request] Anti-Camp and Disable Nukes Game End Plugins

### ISSUE THREAD

**Issue by MrAmos123** [RaidMax/IW4M-Admin#43]
Can you create a plugin that will allow nukes but will not stop/restart the game, it will kill everyone and everyone will respawn and continue the game?

***

Anti-Camp just to !warn <player> for camping and 3 offences will kick them. (For it to restart the counter again)

***

EDIT: A lot of people on my servers are crying about campers so if you do end up making one I'd appreciate it.

**Comment by RaidMax** [comment]
Closing this as not a feature I plan on adding in the near future.
