### ISSUE TITLE
unnessecary if in anticheat

### ISSUE THREAD

**Issue by Bluscream** [RaidMax/IW4M-Admin#45]
https://github.com/RaidMax/IW4M-Admin/blob/master/Plugins/Stats/Cheat/Detection.cs#L197

Shouldn't the second if differenciate from the first? Otherwise you could just omit one of them

**Comment by RaidMax** [comment]
Looks like it should be

if (currentHeadshotRatio > maxHeadshotLerpValueForBan)

**Comment by RaidMax** [comment]
Fixed in https://github.com/RaidMax/IW4M-Admin/commit/270be7ad998fd762f67993fefbe090a76d7a515c

**Comment by Bluscream** [comment]
Thanks mate :)

**Comment by RaidMax** [comment]
Yep, prerelease 6 on my website. Aka 2.16
