### ISSUE TITLE
all text in client's locale

### ISSUE THREAD

**Issue by RaidMax** [RaidMax/IW4M-Admin#46]
What if all the messages from IW4MAdmin were tailored for each client's language?
That is the language would be determined by the IP address of the client.
Rather than a global setting for the language, it could be per client. 
When an Italian client gets kicked (ie VPN usage), it will display the message in Italian.

**Comment by Bluscream** [comment]
Makes sense, thanks for explaining this in detail for yourself :D

**Comment by tow-wang** [comment]
中国不能访问外网。如果挂载其他地区的VPN那么如何显示中文

**Comment by RaidMax** [comment]
closing this for now as it's not on the roadmap for the time being
