### ISSUE TITLE
Add 2 day tempban on profile page

### ISSUE THREAD

**Issue by MASHPOTATOESSS** [RaidMax/IW4M-Admin#47]
Usally I tempban users with being toxic and abusing the warnings/report system. would be handy to have that on the webpage.
 ![image](https://user-images.githubusercontent.com/38188579/45458592-5a517a80-b6c2-11e8-9e4a-c2e1baca2c7b.png)

**Comment by RaidMax** [comment]
Added in https://github.com/RaidMax/IW4M-Admin/commit/46969fc12f990de398bfbac5fd6caa6a1d5e0911
