### ISSUE TITLE
IW4: Crossfire regular map name is missing on homepage

### ISSUE THREAD

**Issue by MASHPOTATOESSS** [RaidMax/IW4M-Admin#48]
![image](https://user-images.githubusercontent.com/38188579/45466281-e8d7f300-b6e6-11e8-89e3-0981483ec4f3.png)

As requested on discord. here is the list of maps...

mp_afghan        	- Afghan
mp_derail        	- Derail
mp_estate        	- Estate
mp_favela        	- Favela
mp_highrise      	- Highrise
mp_invasion      	- Invasion
mp_checkpoint    	- Karachi
mp_quarry        	- Quarry
mp_rundown       	- Rundown
mp_rust          	- Rust
mp_boneyard      	- Scrapyard
mp_nightshift    	- Skidrow
mp_subbase       	- Sub Base
mp_terminal      	- Terminal
mp_underpass     	- Underpass
mp_brecourt      	- Wasteland
mp_complex       	- Bailout
mp_crash         	- Crash
mp_overgrown     	- Overgrown
mp_compact       	- Salvage
mp_storm         	- Storm
mp_abandon       	- Carnival
mp_fuel2         	- Fuel
mp_strike        	- Strike
mp_trailerpark   	- Trailer Park
mp_vacant        	- Vacant
mp_nuked  	   	- Nuketown
mp_cross_fire    	- Crossfire
mp_bloc		    	- Bloc
mp_cargoship     	- Cargoship
mp_killhouse	   	- Killhouse
mp_bog_sh	    	- Bog
mp_cargoship_sh         - Freighter
mp_shipment_long 	- Shipment Long
mp_rust_long     	- Rust Long
mp_firingrange		- Firing Range
mp_storm_spring 	- Chemical Plant
mp_fav_tropical 	- Tropical Favela
mp_estate_tropical 	- Tropical Estate
mp_crash_tropical 	- Tropical Crash
mp_bloc_sh 	        - Forgotten City
oilrig	  	        - Oilrig
iw4_credits     	- Test map
co_hunted	        - Village

**Comment by RaidMax** [comment]
updated in https://github.com/RaidMax/IW4M-Admin/commit/9295f9aa5bf8394c24e76d00a700360f8ad38171
