### ISSUE TITLE
[Feature Request] List of All Clients

### ISSUE THREAD

**Issue by CyferShepard** [RaidMax/IW4M-Admin#49]
Have a page that shows all clients that had connected (Even offline ones) to your server and then use the search filter to display results for the search.

**Comment by RaidMax** [comment]
This used to be a feature. However, I removed it as there wasn't an immediate purpose other than searching.

What exactly would you use it for?
The current search function will display a list of all clients.
![](http://screen.keylog.me/WinKits.png)

**Comment by CyferShepard** [comment]
Call it a combination of OCD and Programing practice, too used to having those 2 functionalities work hand in hand, but i was just asking for personal preference and understand it being set to low priority,
