### ISSUE TITLE
IW4x

### ISSUE THREAD

**Issue by djspike2k8** [RaidMax/IW4M-Admin#5]
It's not showing up on iw4x.exe server, now i don't know if i'm doing something wrong.. says not detected. But it say's that's its for iw4x

**Comment by RaidMax** [comment]
It wasn't designed for IW4X servers. I wrote the description years before IW4X was a thing. I was meaning 'X' as in all the clients based off of aIW (IW4Play, RepZ, React, V2, etc..,).

To get it to work, just rename your server exe to iw4m.exe.

**Comment by djspike2k8** [comment]
ok thanks dude, by the way it looks real good,  i saw it on a video and just thought wow wouldn't mind trying that. :)

**Comment by RaidMax** [comment]
If you're using compiling it yourself, try this precompiled version instead.
http://raidmax.org/downloads/IW4MAdmin_1.2Beta2.zip

**Comment by RaidMax** [comment]
Closing as the newest branch has been massively refactored and supports IW4X
