### ISSUE TITLE
[FR] Ignore bots

### ISSUE THREAD

**Issue by xerxes-at** [RaidMax/IW4M-Admin#51]
Add a setting to completely ignore in-game bots, so the DB won't be spammed with useless profiles.

**Comment by MrAmos123** [comment]
I think this is now fixed in the latest prerelease. (2.2-prerelease9r1)

I don't see the bots in any of my searches.

**Comment by xerxes-at** [comment]
It isn't.

`Debug: Client slot #0 now reserved
Debug: Client /dev /full::-513 first time connecting
Info: Client /dev /full::-513 connected...
Info: Adding /dev /full::-513 to stats
Debug: Client slot #1 now reserved
Debug: Client /dev /random::-514 first time connecting
Info: Client /dev /random::-514 connected...
Info: Adding /dev /random::-514 to stats
Debug: Client slot #2 now reserved
Debug: Client /dev /sdb::-515 first time connecting
Info: Client /dev /sdb::-515 connected...
Info: Adding /dev /sdb::-515 to stats
Debug: Client slot #3 now reserved
Debug: Client /dev /tty0::-517 first time connecting
Info: Client /dev /tty0::-517 connected...
Info: Adding /dev /tty0::-517 to stats`

**Comment by RaidMax** [comment]
Yeah the bots are registered on connect. Ignoring bots shouldn’t be a problem. I’ll try to include it soon.
