### ISSUE TITLE
[FR] RSS feed in AutoMessages

### ISSUE THREAD

**Issue by xerxes-at** [RaidMax/IW4M-Admin#53]
Most forum software has support to access a section as rss feed, it would be nice to be able to use those feeds as a source for in-game news. For example about the community that is hosting the servers, that way an admin only has to post something in the forum and the bot automatically uses the title as in-game auto message. There is a [B3 plugin](https://github.com/BigBrotherBot/big-brother-bot/blob/master/b3/conf/plugin_adv.xml) with this functionality as an example.

**Comment by RaidMax** [comment]
implemented in cd49a98

**Comment by Bluscream** [comment]
Cool
