### ISSUE TITLE
[FR] Log Rotation

### ISSUE THREAD

**Issue by MrAmos123** [RaidMax/IW4M-Admin#55]
Could you also add log rotation for IW4M?

Might be worth dedicating a folder for `logs`.

Cap the log rotation at 10~ logs with the archived logs being appended with `.1, .2, .3, .4, .5` etc respectively. 

Example:
```
IW4MAdmin.log
IW4MAdmin.log.1
IW4MAdmin.log.2
IW4MAdmin.log.3
...
```

**Comment by RaidMax** [comment]
Implemented
