### ISSUE TITLE
Unresponsive server should not stop the bot from starting

### ISSUE THREAD

**Issue by xerxes-at** [RaidMax/IW4M-Admin#58]
A unresponsive server (eg it crashed) should not stop the bot from starting up.

>Error: Not monitoring server due to uncorrectable errors [138.201.26.173:498]
>Debug: Could not get the dvar value for version (ensure the server has a map loaded)
>Error: Could not add server to server stats - An error occurred while updating the entries. See the inner exception for details.
>Fatal error during initialization
>Exception: DVAR "version" does not exist

**Comment by RaidMax** [comment]
implemented in ce40c86
