### ISSUE TITLE
[FR] Add a whitelist of allowed IPs for the webfront.

### ISSUE THREAD

**Issue by xerxes-at** [RaidMax/IW4M-Admin#59]
Add a whitelist of IPs that are allowed to connect to the webfront and instantly close all others.
This would make the discovery of IW4M-Admin with a port scanner much harder and prevents malicious users from bypassing a downstream web-server like nginx.

**Comment by RaidMax** [comment]
Implemented
![image](https://user-images.githubusercontent.com/6732771/52893079-47a20c80-315e-11e9-9c2b-e97abcbea283.png)
