### ISSUE TITLE
[Plugin] Use V2 screenshot ability for server security

### ISSUE THREAD

**Issue by Bluscream** [RaidMax/IW4M-Admin#6]
I imagine something like taking a screenshot of every player on join and if anything fails `error: could not get screenshot` it kicks the player.

After time it could get more advanced, like analizing the image and kicking if colors are less then 2 or suspicious boxes detected.

**Comment by RaidMax** [comment]
Closed as V2 IW4 is now defunct. Any additional suggestions for the IW4X branch are welcome.

**Comment by Bluscream** [comment]
You we're a dev, so give them the screenshot code xD
