### ISSUE TITLE
[FR] Overload Utilities.Prompt... methods.

### ISSUE THREAD

**Issue by xerxes-at** [RaidMax/IW4M-Admin#65]
Add a overload for the following methods to provide a reasonable default value to assist the user.
Additionally a string variable for a help text could be added as well to make it more clear what a setting does / assist the user in choosing a correct value for his needs.
Utilities.PromptBool
Utilities.PromptInt
Utilities.PromptString

**Comment by RaidMax** [comment]
Implemented in 7aad7cd
