### ISSUE TITLE
Additional option of sorting Most Played by playtime instead of kills

### ISSUE THREAD

**Issue by Jawesome99** [RaidMax/IW4M-Admin#68]
![](https://media.discordapp.net/attachments/313023558479511552/549683949241368578/unknown.png)  
↓  
![](https://media.discordapp.net/attachments/313023558479511552/549683889774264324/unknown_-_Copy.png)

Currently, the "Most Played" list is oddly sorted by Kill Count instead of Time Played. An option to switch to Time Played sorting would be really appreciated.

**Comment by RaidMax** [comment]
updated in 98fba11
