### ISSUE TITLE
Enhancement: Per game kick messages for the name filter

### ISSUE THREAD

**Issue by xerxes-at** [RaidMax/IW4M-Admin#74]
PlutoT6 doesn't like a / in front of commands so the command `/name` in the kick message for DisallowedClientNames won't work while `name` does work.

`Please change your name using /name ` should become `Please change your name using 'name' ` for PlutoT6.

**Comment by RaidMax** [comment]
I changed this a while back in the translation sheet to `Your name is not allowed on this server. Please change it`, I think that should be general enough for all clients.
