### ISSUE TITLE
Enhancement: Show which filter triggered a warning from the Profanity Determent

### ISSUE THREAD

**Issue by xerxes-at** [RaidMax/IW4M-Admin#75]
Working with long profanity lists, that cover multiple languages, can be annoying and tedious when trying to figure out what causes a warning even though nothing bad has been said / used as a name. Showing which line caused the Profanity Determent to warn / kick a player would ease that and put that unused space to a good use.

![empty space](https://media.discordapp.net/attachments/495870833131257858/594615843636117524/unknown.png)

**Comment by RaidMax** [comment]
I think this is a good idea. I'll add it to the 2.4 roadmap

**Comment by RaidMax** [comment]
Implemented in 7f388a1
