### ISSUE TITLE
Unreadable characters

### ISSUE THREAD

**Issue by zorro-one** [RaidMax/IW4M-Admin#78]
1) I can’t understand how to make the characters "?????????????" readable.
2) Is it possible to hide "{{mapName}}"?
![NapName_01](https://user-images.githubusercontent.com/53860363/62616233-b430e380-b917-11e9-93a6-dd9659c0b9e6.png)

3) Is it possible to set up autokick for players using a certain killstreak?

**Comment by RaidMax** [comment]
> 1. I can’t understand how to make the characters "?????????????" readable.
Use pre release version
> 2. Is it possible to hide "{{mapName}}"?
>    ![NapName_01](https://user-images.githubusercontent.com/53860363/62616233-b430e380-b917-11e9-93a6-dd9659c0b9e6.png)
Use pre release version
> 3. Is it possible to set up autokick for players using a certain killstreak?
Nope, that's a game specific implementation. I try to make IW4MAdmin as holistic as possible across games, so I like to try to develop features that can be used on an CoD game.

Between 2.2 and 2.3 pre release I made a necessary breaking change to how translations are handled. What is the language of your server machine set to?

**Comment by zorro-one** [comment]
Sorry, I did not specify the version of IW4MAdmin and the localization of the server PC.
Version IW4MAdmin-2.2-stable
Server PC Localization - Russian

**Comment by RaidMax** [comment]
Latest pre-release will solve the issues.
If you don't want to have IW4MAdmin automatically choose the encoding, change the encoding.

```"EnableCustomParserEncoding": true,
"CustomParserEncoding": "windows-1252"```

**Comment by zorro-one** [comment]
Thank! After upgrading to Version 2.3 Pre-Release 8 Revision 0, problems with unreadable characters were resolved. However, other problems appeared, which I will discuss in the relevant topic.

Finally, another question. Is it possible to change the color of the map name through the config using ^ 1, ^ 2, ^ 3, etc.?
![NapName_03](https://user-images.githubusercontent.com/53860363/62707666-6fca4400-b9fa-11e9-89d5-a8edd014d85c.png)

**Comment by RaidMax** [comment]
Yes it is possible. The text for this information is stored in the translation/localization file. 
By default IW4MAdmin uses an online copy of the translation file so you always have the most up to date version. You can override this behavior in the `IW4MAdminSettings.json`

Set ` "UseLocalTranslations": true,`

That will make IW4MAdmin use the files in the `Localization` folder.

Since it looks like you're using the en-US translation look for:
`  "COMMANDS_NEXTMAP_SUCCESS": "The next map is {{mapName}}/{{gameMode}}",`

and add your color codes as needed

**Comment by zorro-one** [comment]
Thanks! Now everything works great!
![MapName_04](https://user-images.githubusercontent.com/53860363/62717082-e885cc00-ba0b-11e9-8bfa-0f851a4e4546.png)

By the way, where does IW4MAdmin get the {{gameMode}} variable?

**Comment by RaidMax** [comment]
https://github.com/RaidMax/IW4M-Admin/blob/master/SharedLibraryCore/Utilities.cs#L221  

It’s currently in source code but I’d like to move it into translations eventually

**Comment by zorro-one** [comment]
Thanks!
