### ISSUE TITLE
How do customize Welcome message.

### ISSUE THREAD

**Issue by AhmadQamar5** [RaidMax/IW4M-Admin#8]
Can you guide me on how to change the welcome message as the WelcomePlugin.dll file is encrypted and if we could change the syntax when a player joins the server because I could not find any customizable welcome config e.t.c.

**Comment by RaidMax** [comment]
If you're compiling from source (which doesn't really work right now as I'm in a transitioning state), you can modify https://github.com/RaidMax/IW4M-Admin/blob/master/Plugins/Welcome/Plugin.cs#L98
I'll be sure to add the ability to provide custom welcome messages in the next major release.

**Comment by RaidMax** [comment]
As requested this feature will be implemented in the next release, here's an example:

http://screen.keylog.me/UnixesSnark.png
