### ISSUE TITLE
[FR] Generate a command overview for the webinterface.

### ISSUE THREAD

**Issue by xerxes-at** [RaidMax/IW4M-Admin#89]
Since it is possible to introduce custom commands with C# plug-ins and soon will be possible with JS plug-ins as well there should be a list of commands available on webinterface as well.

The list should be generated by the privileges of the viewing user and all registered commands so it shows the commands from IW4mA itself, the shipped plug-ins and from custom plug-ins a user has access to. This list should also be visible to users not logged in as there are commands that can be run by unprivileged clients like `!ping` or `!votekick`

**Comment by RaidMax** [comment]
I like this idea

**Comment by RaidMax** [comment]
Implemented in 142924e
