### ISSUE TITLE
games_mp.log does not exist

### ISSUE THREAD

**Issue by AbodeRules** [RaidMax/IW4M-Admin#9]
When i try to run the admin mod it gives me this error games_mp.log does not  exist! 
![screenshot_1](https://user-images.githubusercontent.com/34998881/34466926-8db4ff96-eef4-11e7-8e26-0ac7ab31a58f.png)
![screenshot_3](https://user-images.githubusercontent.com/34998881/34466927-8de201d0-eef4-11e7-94cf-ee7348d36588.png)

**Comment by RaidMax** [comment]
Are you running the server over a networked drive?

**Comment by RaidMax** [comment]
Closing as no response.
