### ISSUE TITLE
[FIX][Enhancement] Use sv_running to detect servers that are offline.

### ISSUE THREAD

**Issue by xerxes-at** [RaidMax/IW4M-Admin#91]
Under certain circumstances IW4m-Admin can not detect if a server is down and shows an server that is not running a map as online. This can easily happen on T6 due to the server still responding to rcon queries, however the current server state can also be read as a bool from `sv_running` which exists as far as I know in every CoD Title and behaves the same way.

## T6
![grafik](https://user-images.githubusercontent.com/5236639/71678379-5056fd80-2d85-11ea-8962-fa0239ed0443.png)

![grafik](https://user-images.githubusercontent.com/5236639/71678397-5c42bf80-2d85-11ea-94de-164e7c8fd0ac.png)

## IW4

![grafik](https://user-images.githubusercontent.com/5236639/71678576-c52a3780-2d85-11ea-9486-9ef5b033a91f.png)

## T5

![grafik](https://user-images.githubusercontent.com/5236639/71678607-d3785380-2d85-11ea-80b7-5dea1c80f1d8.png)

**Comment by RaidMax** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Use sv_running to detect servers that are offline](https://trello.com/c/y0a9TgQw/77-use-svrunning-to-detect-servers-that-are-offline)

**Comment by RaidMax** [comment]
implemented in 88d99d1
