### ISSUE TITLE
[Bug] IW4mAdmin exits after !restart command

### ISSUE THREAD

**Issue by Jawesome99** [RaidMax/IW4M-Admin#95]
Issuing the `!restart` command will first restart IW4mAdmin, reconnect to the servers, then exit shortly after.

![](https://puu.sh/EZvxh/7c5fb1d37d.png)

Entering commands a few times won't send any response, but may speed up the time it takes until it exits.

**Comment by RaidMax** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [!restart command aberrant behavior](https://trello.com/c/MoQy1uhS/78-restart-command-aberrant-behavior)

**Comment by RaidMax** [comment]
Fixed in 9330e805
