### ISSUE TITLE
Top Players Bug

### ISSUE THREAD

**Issue by BLANKxSS** [RaidMax/IW4M-Admin#99]
when i go in top players
i getting this error

Website Error:
Sorry!
Something happened when creating this page

console error:
Error: [Webfront] An item with the same key has already been added. Key: 1367

**Comment by RaidMax** [comment]
Looks like the .NET Core upgrade changed something about the way top stats are queried. Will look into this soon.

**Comment by ChaseHall** [comment]
@BLANKxSS are you still having this issue with the latest version of IW4MAdmin?

**Comment by RaidMax** [comment]
Closing this unless it is reproducible. Could not reproduce it.
